const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const base=path.resolve(__dirname,'../build/test-'+Date.now()+'-中文');fs.mkdirSync(base,{recursive:true});
const cli=path.resolve(__dirname,'../dist/tcmod-cli.exe');let count=0;
const crc=b=>{let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;};
function zip(entries){let chunks=[],central=[],offset=0;for(let [name,data] of entries){const n=Buffer.from(name),b=Buffer.from(data),h=Buffer.alloc(30),c=Buffer.alloc(46);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt32LE(crc(b),14);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt32LE(crc(b),16);c.writeUInt32LE(b.length,20);c.writeUInt32LE(b.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);chunks.push(h,n,b);central.push(c,n);offset+=h.length+n.length+b.length;}const cb=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(cb.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...chunks,cb,end]);}
function fixture(name){const d=path.join(base,name);fs.mkdirSync(path.join(d,'mods'),{recursive:true});fs.mkdirSync(path.join(d,'translations'),{recursive:true});fs.writeFileSync(path.join(d,'translations/test.txt'),'original');return d;}
function mod(d,id,files,extra={}){const m={format:1,id,name:id,version:'1.0.0',...extra};fs.writeFileSync(path.join(d,'mods',id+'.mod'),zip([['mod.json',JSON.stringify(m)],...Object.entries(files).map(([p,v])=>['files/'+p,v])]));}
function run(d,args,ok=true,match){const r=cp.spawnSync(cli,[d,...args],{encoding:'utf8'});if((r.status===0)!==ok||match&&!((r.stdout+r.stderr).includes(match)))throw Error(JSON.stringify({args,...r}));return r;}
function runRaw(args,ok=true,match){const r=cp.spawnSync(cli,args,{encoding:'utf8'});if((r.status===0)!==ok||match&&!((r.stdout+r.stderr).includes(match)))throw Error(JSON.stringify({args,...r}));return r;}
function check(name,fn){fn();count++;console.log('PASS '+name);}
function eq(a,b){if(a!==b)throw Error(`${a} != ${b}`);}
let d=fixture('basic');mod(d,'demo',{'translations/test.txt':'modded','asset/new.txt':'added'});
check('the CLI reports the version in VERSION',()=>{const expected=fs.readFileSync(path.resolve(__dirname,'../VERSION'),'utf8').trim();runRaw(['--version'],true,'tcmod-cli '+expected);});
check('the CLI lists the capability names mod.json may ask for',()=>{const names=runRaw(['--capabilities']).stdout.trim().split(/,\s*/);for(const name of ['log','hook','logic','component','ui_page','ui_slot','texture','status'])if(!names.includes(name))throw Error('missing capability '+name);});
check('list valid package',()=>run(d,['list'],true,'demo'));
check('apply changes original and adds file',()=>{run(d,['apply','demo']);eq(fs.readFileSync(path.join(d,'translations/test.txt'),'utf8'),'modded');eq(fs.readFileSync(path.join(d,'asset/new.txt'),'utf8'),'added');});
check('repeated apply is idempotent',()=>run(d,['apply','demo']));
check('disable restores original and removes added file',()=>{run(d,['disable-all']);eq(fs.readFileSync(path.join(d,'translations/test.txt'),'utf8'),'original');eq(fs.existsSync(path.join(d,'asset/new.txt')),false);});
mod(d,'conflict',{'translations/TEST.txt':'other'});
check('case-insensitive conflict rejected before writes',()=>{run(d,['apply','demo','conflict'],false,'File conflict');eq(fs.readFileSync(path.join(d,'translations/test.txt'),'utf8'),'original');});
check('missing dependency rejected',()=>{mod(d,'dependent',{'asset/dependent.txt':'x'},{requires:['demo']});run(d,['apply','dependent'],false,'requires demo');});
check('dependencies accepted together',()=>run(d,['apply','demo','dependent']));
check('declared capability accepted',()=>{const f=fixture('caps-ok');mod(f,'wants',{'asset/wants.txt':'x'},{capabilities:['status','ui_slot']});run(f,['list'],true,'wants');run(f,['apply','wants']);});
check('unknown capability rejected while scanning',()=>{const f=fixture('caps-unknown');mod(f,'wants',{'asset/wants.txt':'x'},{capabilities:['telepathy']});run(f,['list'],true,'Unknown loader capability: telepathy');run(f,['apply','wants'],false,'Missing or invalid');});
check('satisfied dependency constraint accepted',()=>{const f=fixture('dep-ok');mod(f,'core',{'asset/core.txt':'1'});mod(f,'plugin',{'asset/plugin.txt':'2'},{requires:{core:'>=1.0.0'}});run(f,['apply','core','plugin']);});
check('unsatisfied dependency constraint rejected before writes',()=>{const f=fixture('dep-old');mod(f,'core',{'asset/core.txt':'1'});mod(f,'plugin',{'asset/plugin.txt':'2'},{requires:{core:'>=2.0.0'}});run(f,['apply','core','plugin'],false,'enabled version is 1.0.0');eq(fs.existsSync(path.join(f,'asset/plugin.txt')),false);});
check('version comparison is numeric, not lexical',()=>{const f=fixture('dep-numeric');mod(f,'core',{'asset/core.txt':'1'},{version:'1.9.0'});mod(f,'plugin',{'asset/plugin.txt':'2'},{requires:{core:'>=1.10.0'}});run(f,['apply','core','plugin'],false,'enabled version is 1.9.0');});
check('missing optional dependency accepted',()=>{const f=fixture('opt-missing');mod(f,'solo',{'asset/solo.txt':'1'},{optional:{friend:'>=1.0.0'}});run(f,['apply','solo']);});
check('enabled optional dependency still checked',()=>{const f=fixture('opt-old');mod(f,'friend',{'asset/friend.txt':'1'},{version:'0.9.0'});mod(f,'solo',{'asset/solo.txt':'1'},{optional:{friend:'>=1.0.0'}});run(f,['apply','solo','friend'],false,'enabled version is 0.9.0');run(f,['apply','solo']);});
check('a version constraint cannot be a number',()=>{const f=fixture('dep-shape');mod(f,'bad',{'asset/bad.txt':'1'},{requires:{friend:2}});run(f,['list'],true,'version constraints must be strings');});
check('external edit protected on disable',()=>{fs.writeFileSync(path.join(d,'translations/test.txt'),'user edit');run(d,['disable-all'],false,'outside loader');eq(fs.readFileSync(path.join(d,'translations/test.txt'),'utf8'),'user edit');});
check('can restore after reconciling external change',()=>{fs.writeFileSync(path.join(d,'translations/test.txt'),'modded');run(d,['disable-all']);});
check('missing package can still be disabled',()=>{run(d,['apply','demo']);fs.unlinkSync(path.join(d,'mods/demo.mod'));run(d,['disable-all']);eq(fs.readFileSync(path.join(d,'translations/test.txt'),'utf8'),'original');});
check('missing selected package is rejected',()=>run(d,['apply','demo'],false,'Missing or invalid'));
for(const [name,p] of [['traversal','../escape'],['absolute','C:/escape'],['backslash','asset\\bad'],['device','asset/CON.txt'],['stream','asset/x:y'],['unknownroot','bin/test.dll'],['dot','asset/x.']])check('reject '+name,()=>{const f=fixture(name);mod(f,'evil',{[p]:'x'});run(f,['apply','evil'],false);eq(fs.readFileSync(path.join(f,'translations/test.txt'),'utf8'),'original');});
check('duplicate IDs rejected',()=>{const f=fixture('duplicate');mod(f,'same',{'asset/a':'x'});fs.copyFileSync(path.join(f,'mods/same.mod'),path.join(f,'mods/second.mod'));run(f,['list'],true,'Duplicate Mod id');run(f,['apply','same'],false);});
check('corrupt archive rejected',()=>{const f=fixture('corrupt');fs.writeFileSync(path.join(f,'mods/broken.mod'),'invalid');run(f,['list'],true,'Not a valid');});
check('text patch apply, repeat and restore',()=>{const f=fixture('patch');mod(f,'patch',{}, {patches:[{path:'translations/test.txt',find:'original',replace:'patched'}]});run(f,['apply','patch']);eq(fs.readFileSync(path.join(f,'translations/test.txt'),'utf8'),'patched');run(f,['apply','patch']);run(f,['disable-all']);eq(fs.readFileSync(path.join(f,'translations/test.txt'),'utf8'),'original');});
check('text patch mismatch rejected without changes',()=>{const f=fixture('patch-mismatch');mod(f,'patch',{}, {patches:[{path:'translations/test.txt',find:'absent',replace:'patched'}]});run(f,['list'],true,'exactly once');run(f,['apply','patch'],false);eq(fs.readFileSync(path.join(f,'translations/test.txt'),'utf8'),'original');});
check('text patch multiple matches rejected',()=>{const f=fixture('patch-multiple');fs.writeFileSync(path.join(f,'translations/test.txt'),'xx');mod(f,'patch',{}, {patches:[{path:'translations/test.txt',find:'x',replace:'y'}]});run(f,['list'],true,'exactly once');});
check('interrupted transaction rolls back from verified blob',()=>{const f=fixture('recovery');run(f,['list']);let p=path.join(f,'tc-modloader-data');let before=crypto.createHash('sha256').update('original').digest('hex'),after=crypto.createHash('sha256').update('partial').digest('hex');fs.writeFileSync(path.join(p,'blobs',before),'original');fs.writeFileSync(path.join(f,'translations/test.txt'),'partial');fs.writeFileSync(path.join(p,'transaction.json'),JSON.stringify({id:'interrupted',changes:[{path:'translations/test.txt',before,after}]}));run(f,['list']);eq(fs.readFileSync(path.join(f,'translations/test.txt'),'utf8'),'original');eq(fs.existsSync(path.join(p,'transaction.json')),false);});
check('recovery preserves externally modified file',()=>{const f=fixture('recovery-edited');run(f,['list']);let p=path.join(f,'tc-modloader-data');fs.writeFileSync(path.join(p,'transaction.json'),JSON.stringify({id:'x',changes:[{path:'translations/test.txt',before:'a',after:'b'}]}));run(f,['list'],false,'Recovery stopped');eq(fs.readFileSync(path.join(f,'translations/test.txt'),'utf8'),'original');});
console.log(`${count} tests passed; fixtures retained at ${base}`);
fs.writeFileSync(path.resolve(__dirname,'../build/test-results.txt'),`${count} integration tests passed\nFixtures: ${base}\n`);
module.exports={zip};
