#!/usr/bin/env python3
"""Turn the game's own prototype table into the pin geometry the loader uses.

`build/kinds.txt` is a dump of the pinned build's 125 built-in prototypes
(tests/kind-list-playtest.ps1 writes it).  Automatic feedback cutting needs to
know where a component's pins sit, and guessing them is what made an earlier
version cut ordinary connections; the game's table is the authority.

Only **combinational** prototypes are emitted.  A cut is only legal where the
game itself would refuse to compile the loop: a cycle through a state-holding
part (Delay Line, Register, RAM, Counter, Switch, ...) is something the game
compiles happily, so cutting it would break a working circuit instead of
legalising a refused one.  Custom components are left out for the same reason -
their internals are unknown here, so we cannot tell whether an instance is
combinational.

Usage:  python tools/generate-gate-pins.py [kinds.txt] [out.hpp]
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

PIN = re.compile(r"(in|out)(\d+)=\((-?\d+),(-?\d+),w(-?\d+)\)")
ENTRY = re.compile(r'^0x([0-9a-f]+) name="([^"]*)" .*?inputs=(\d+) outputs=(\d+)(.*)$')

# Prototypes that hold state, drive the outside world, or are otherwise not
# something a combinational loop may pass through.  Matched on the game's name:
# anything with these words in it is left out.
STATEFUL_WORDS = (
    "Delay", "Register", "Counter", "Switch", "RAM", "Memory Probe", "Probe Memory",
    "Screen", "Keyboard", "Time", "Push Button", "Static Evaluator", "Level Component",
)
# Custom components and their pins are not part of the built-in table.
SKIP_KINDS = {0x00, 0x4E, 0x4F, 0x51}


def parse(path: pathlib.Path):
    entries = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("0x"):
            continue
        match = ENTRY.match(line.strip())
        if not match:
            continue
        kind = int(match.group(1), 16)
        name = match.group(2)
        declared = (int(match.group(3)), int(match.group(4)))
        inputs, outputs = [], []
        for role, index, x, y, _width in PIN.findall(match.group(5)):
            target = inputs if role == "in" else outputs
            target.append((int(index), int(x), int(y)))
        entries.append({"kind": kind, "name": name, "declared": declared,
                        "inputs": sorted(inputs), "outputs": sorted(outputs)})
    return entries


def accepted(entries):
    """The prototypes a combinational loop may pass through."""
    keep = []
    for entry in entries:
        kind, name = entry["kind"], entry["name"]
        if kind in SKIP_KINDS or not name:
            continue
        if any(word in name for word in STATEFUL_WORDS):
            continue
        want_in, want_out = entry["declared"]
        if len(entry["inputs"]) != want_in or len(entry["outputs"]) != want_out:
            continue                       # incomplete geometry: do not guess
        if want_in + want_out == 0:
            continue
        if not want_out or not want_in:
            continue                       # a source or a sink carries no loop
        pins = entry["inputs"] + entry["outputs"]
        if any(abs(x) > 64 or abs(y) > 64 for _, x, y in pins):
            continue                       # placeholder geometry
        if len(entry["inputs"]) > 8 or len(entry["outputs"]) > 4:
            continue
        keep.append(entry)
    return keep


def emit(entries, path: pathlib.Path):
    lines = [
        "#pragma once",
        "/* Generated by tools/generate-gate-pins.py from the pinned build's own",
        "   prototype table (build/kinds.txt, 2.1.334).  Do not edit by hand:",
        "   re-run the generator, which also refuses any prototype whose pin",
        "   geometry is incomplete.  Only combinational prototypes are listed -",
        "   see the generator's header for why. */",
        "namespace tc {",
        "namespace gate_delay {",
        "",
        "struct KindPins {",
        "    uint8_t kind = 0;",
        "    uint8_t inCount = 0, outCount = 0;",
        "    int8_t inX[8] = {}, inY[8] = {};",
        "    int8_t outX[4] = {}, outY[4] = {};",
        "};",
        "",
        "inline const KindPins kBuiltinKindPins[] = {",
    ]
    for entry in sorted(entries, key=lambda item: item["kind"]):
        ins = ", ".join(str(x) for _, x, _ in entry["inputs"])
        insy = ", ".join(str(y) for _, _, y in entry["inputs"])
        outs = ", ".join(str(x) for _, x, _ in entry["outputs"])
        outsy = ", ".join(str(y) for _, _, y in entry["outputs"])
        lines.append("    {0x%02x, %d, %d, {%s}, {%s}, {%s}, {%s}},  // %s" % (
            entry["kind"], len(entry["inputs"]), len(entry["outputs"]),
            ins, insy, outs, outsy, entry["name"]))
    lines += ["};", "",
              "inline const KindPins* builtinKindPins(uint8_t kind) {",
              "    for (const KindPins& entry : kBuiltinKindPins)",
              "        if (entry.kind == kind) return &entry;",
              "    return nullptr;",
              "}",
              "",
              "}  // namespace gate_delay",
              "}  // namespace tc",
              ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("kinds", nargs="?", default="build/kinds.txt")
    parser.add_argument("out", nargs="?", default="src/gate_pins.generated.hpp")
    args = parser.parse_args()
    path = pathlib.Path(args.kinds)
    if not path.exists():
        print(f"missing {path}; run tests/kind-list-playtest.ps1 first", file=sys.stderr)
        return 1
    entries = parse(path)
    keep = accepted(entries)
    emit(keep, pathlib.Path(args.out))
    print(f"parsed {len(entries)} prototypes, emitted {len(keep)} combinational ones")
    for entry in sorted(keep, key=lambda item: item["kind"]):
        print("  0x%02x %-22s in=%d out=%d" % (
            entry["kind"], entry["name"], len(entry["inputs"]), len(entry["outputs"])))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
