#include <cstddef>
#include <cstdint>
#include <iostream>
#include <type_traits>
#include "../sdk/tc_mod_api.h"

static void record(const char* name, std::uint64_t value) {
    std::cout << name << '=' << value << '\n';
}
static void record_signed(const char* name, std::int64_t value) {
    std::cout << name << '=' << value << '\n';
}

#define ABI_SIZE(type) record("sizeof." #type, sizeof(type))
#define ABI_ALIGN(type) record("alignof." #type, alignof(type))
#define ABI_LAYOUT(type) record("standard-layout." #type, std::is_standard_layout<type>::value ? 1u : 0u)
#define ABI_OFFSET(type, field) record("offsetof." #type "." #field, offsetof(type, field))
#define ABI_CONSTANT(name) record("constant." #name, static_cast<std::uint64_t>(name))
#define ABI_SIGNED_CONSTANT(name) record_signed("constant." #name, static_cast<std::int64_t>(name))

int main() {
    record("meta.pointer-size", sizeof(void*));
    record("meta.function-pointer-size", sizeof(TCModLoad));

    ABI_SIZE(TCFrame); ABI_ALIGN(TCFrame); ABI_LAYOUT(TCFrame);
    ABI_OFFSET(TCFrame, size); ABI_OFFSET(TCFrame, frame_number); ABI_OFFSET(TCFrame, time_seconds);

    ABI_SIZE(TCUiPageDefinition); ABI_ALIGN(TCUiPageDefinition); ABI_LAYOUT(TCUiPageDefinition);
    ABI_OFFSET(TCUiPageDefinition, size); ABI_OFFSET(TCUiPageDefinition, page_id);
    ABI_OFFSET(TCUiPageDefinition, title); ABI_OFFSET(TCUiPageDefinition, draw); ABI_OFFSET(TCUiPageDefinition, user);

    ABI_SIZE(TCUiSlotDefinition); ABI_ALIGN(TCUiSlotDefinition); ABI_LAYOUT(TCUiSlotDefinition);
    ABI_OFFSET(TCUiSlotDefinition, size); ABI_OFFSET(TCUiSlotDefinition, kind); ABI_OFFSET(TCUiSlotDefinition, slot_id);
    ABI_OFFSET(TCUiSlotDefinition, title); ABI_OFFSET(TCUiSlotDefinition, draw); ABI_OFFSET(TCUiSlotDefinition, user);
    ABI_OFFSET(TCUiSlotDefinition, preferred_width); ABI_OFFSET(TCUiSlotDefinition, preferred_height);

    ABI_SIZE(TCUiTexturePixels); ABI_ALIGN(TCUiTexturePixels); ABI_LAYOUT(TCUiTexturePixels);
    ABI_OFFSET(TCUiTexturePixels, size); ABI_OFFSET(TCUiTexturePixels, width); ABI_OFFSET(TCUiTexturePixels, height);
    ABI_OFFSET(TCUiTexturePixels, filter); ABI_OFFSET(TCUiTexturePixels, rgba); ABI_OFFSET(TCUiTexturePixels, byte_count);
    ABI_SIZE(TCUiTexture); ABI_ALIGN(TCUiTexture); ABI_LAYOUT(TCUiTexture);
    ABI_OFFSET(TCUiTexture, size); ABI_OFFSET(TCUiTexture, width); ABI_OFFSET(TCUiTexture, height);
    ABI_OFFSET(TCUiTexture, reserved); ABI_OFFSET(TCUiTexture, handle); ABI_OFFSET(TCUiTexture, renderer_id);

    ABI_SIZE(TCHost); ABI_ALIGN(TCHost); ABI_LAYOUT(TCHost);
    ABI_OFFSET(TCHost, size); ABI_OFFSET(TCHost, api_version); ABI_OFFSET(TCHost, context);
    ABI_OFFSET(TCHost, game_build); ABI_OFFSET(TCHost, mod_id); ABI_OFFSET(TCHost, data_directory_utf8);
    ABI_OFFSET(TCHost, log); ABI_OFFSET(TCHost, resolve_symbol); ABI_OFFSET(TCHost, engine_proc);
    ABI_OFFSET(TCHost, create_hook); ABI_OFFSET(TCHost, register_logic); ABI_OFFSET(TCHost, register_component);
    ABI_OFFSET(TCHost, register_ui_page); ABI_OFFSET(TCHost, create_ui_texture); ABI_OFFSET(TCHost, load_ui_texture);
    ABI_OFFSET(TCHost, release_ui_texture); ABI_OFFSET(TCHost, register_ui_slot); ABI_OFFSET(TCHost, host_version);
    ABI_OFFSET(TCHost, host_version_reserved); ABI_OFFSET(TCHost, capabilities); ABI_OFFSET(TCHost, report_status);
    ABI_OFFSET(TCHost, resolve_alias); ABI_OFFSET(TCHost, register_hook_chain); ABI_OFFSET(TCHost, add_event_listener);
    ABI_OFFSET(TCHost, get_current_game_handle); ABI_OFFSET(TCHost, validate_game_handle); ABI_OFFSET(TCHost, resolve_game_handle);
    ABI_OFFSET(TCHost, query_service);

    ABI_SIZE(TCGameHandle); ABI_ALIGN(TCGameHandle); ABI_LAYOUT(TCGameHandle);
    ABI_OFFSET(TCGameHandle, size); ABI_OFFSET(TCGameHandle, kind); ABI_OFFSET(TCGameHandle, generation); ABI_OFFSET(TCGameHandle, token);

    ABI_SIZE(TCServiceHeader); ABI_ALIGN(TCServiceHeader); ABI_LAYOUT(TCServiceHeader);
    ABI_OFFSET(TCServiceHeader, size); ABI_OFFSET(TCServiceHeader, version);
    ABI_SIZE(TCBoardApiV1); ABI_ALIGN(TCBoardApiV1); ABI_LAYOUT(TCBoardApiV1);
    ABI_OFFSET(TCBoardApiV1, size); ABI_OFFSET(TCBoardApiV1, version); ABI_OFFSET(TCBoardApiV1, context);
    ABI_OFFSET(TCBoardApiV1, get_current); ABI_OFFSET(TCBoardApiV1, validate); ABI_OFFSET(TCBoardApiV1, resolve);
    ABI_SIZE(TCBoardSnapshotV1); ABI_ALIGN(TCBoardSnapshotV1); ABI_LAYOUT(TCBoardSnapshotV1);
    ABI_OFFSET(TCBoardSnapshotV1, size); ABI_OFFSET(TCBoardSnapshotV1, version); ABI_OFFSET(TCBoardSnapshotV1, board);
    ABI_OFFSET(TCBoardSnapshotV1, engine_frame); ABI_OFFSET(TCBoardSnapshotV1, simulation_cycle);
    ABI_OFFSET(TCBoardSnapshotV1, selected_component_count); ABI_OFFSET(TCBoardSnapshotV1, selected_wire_count);
    ABI_OFFSET(TCBoardSnapshotV1, previous_selected_component_count); ABI_OFFSET(TCBoardSnapshotV1, previous_selected_wire_count);
    ABI_OFFSET(TCBoardSnapshotV1, flags); ABI_OFFSET(TCBoardSnapshotV1, reserved);
    ABI_SIZE(TCBoardApiV2); ABI_ALIGN(TCBoardApiV2); ABI_LAYOUT(TCBoardApiV2);
    ABI_OFFSET(TCBoardApiV2, size); ABI_OFFSET(TCBoardApiV2, version); ABI_OFFSET(TCBoardApiV2, context);
    ABI_OFFSET(TCBoardApiV2, get_current); ABI_OFFSET(TCBoardApiV2, validate); ABI_OFFSET(TCBoardApiV2, resolve);
    ABI_OFFSET(TCBoardApiV2, capture_snapshot);
    ABI_SIZE(TCBoardObjectBuffersV1); ABI_ALIGN(TCBoardObjectBuffersV1); ABI_LAYOUT(TCBoardObjectBuffersV1);
    ABI_OFFSET(TCBoardObjectBuffersV1, size); ABI_OFFSET(TCBoardObjectBuffersV1, version);
    ABI_OFFSET(TCBoardObjectBuffersV1, components); ABI_OFFSET(TCBoardObjectBuffersV1, component_capacity);
    ABI_OFFSET(TCBoardObjectBuffersV1, wires); ABI_OFFSET(TCBoardObjectBuffersV1, wire_capacity);
    ABI_SIZE(TCBoardObjectSnapshotV1); ABI_ALIGN(TCBoardObjectSnapshotV1); ABI_LAYOUT(TCBoardObjectSnapshotV1);
    ABI_OFFSET(TCBoardObjectSnapshotV1, size); ABI_OFFSET(TCBoardObjectSnapshotV1, version);
    ABI_OFFSET(TCBoardObjectSnapshotV1, board); ABI_OFFSET(TCBoardObjectSnapshotV1, engine_frame);
    ABI_OFFSET(TCBoardObjectSnapshotV1, snapshot_generation); ABI_OFFSET(TCBoardObjectSnapshotV1, component_count);
    ABI_OFFSET(TCBoardObjectSnapshotV1, wire_count); ABI_OFFSET(TCBoardObjectSnapshotV1, component_written);
    ABI_OFFSET(TCBoardObjectSnapshotV1, wire_written); ABI_OFFSET(TCBoardObjectSnapshotV1, flags);
    ABI_OFFSET(TCBoardObjectSnapshotV1, reserved);
    ABI_SIZE(TCBoardApiV3); ABI_ALIGN(TCBoardApiV3); ABI_LAYOUT(TCBoardApiV3);
    ABI_OFFSET(TCBoardApiV3, size); ABI_OFFSET(TCBoardApiV3, version); ABI_OFFSET(TCBoardApiV3, context);
    ABI_OFFSET(TCBoardApiV3, get_current); ABI_OFFSET(TCBoardApiV3, validate); ABI_OFFSET(TCBoardApiV3, resolve);
    ABI_OFFSET(TCBoardApiV3, capture_snapshot); ABI_OFFSET(TCBoardApiV3, capture_objects);
    ABI_SIZE(TCComponentInfoV1); ABI_ALIGN(TCComponentInfoV1); ABI_LAYOUT(TCComponentInfoV1);
    ABI_OFFSET(TCComponentInfoV1, size); ABI_OFFSET(TCComponentInfoV1, version); ABI_OFFSET(TCComponentInfoV1, flags);
    ABI_OFFSET(TCComponentInfoV1, kind); ABI_OFFSET(TCComponentInfoV1, handle); ABI_OFFSET(TCComponentInfoV1, id);
    ABI_OFFSET(TCComponentInfoV1, x); ABI_OFFSET(TCComponentInfoV1, y); ABI_OFFSET(TCComponentInfoV1, rotation);
    ABI_OFFSET(TCComponentInfoV1, reserved0); ABI_OFFSET(TCComponentInfoV1, custom_prototype_id);
    ABI_OFFSET(TCComponentInfoV1, reserved1); ABI_OFFSET(TCComponentInfoV1, reserved2);
    ABI_SIZE(TCWireInfoV1); ABI_ALIGN(TCWireInfoV1); ABI_LAYOUT(TCWireInfoV1);
    ABI_OFFSET(TCWireInfoV1, size); ABI_OFFSET(TCWireInfoV1, version); ABI_OFFSET(TCWireInfoV1, flags);
    ABI_OFFSET(TCWireInfoV1, reserved0); ABI_OFFSET(TCWireInfoV1, handle); ABI_OFFSET(TCWireInfoV1, id);
    ABI_OFFSET(TCWireInfoV1, x1); ABI_OFFSET(TCWireInfoV1, y1); ABI_OFFSET(TCWireInfoV1, x2); ABI_OFFSET(TCWireInfoV1, y2);
    ABI_OFFSET(TCWireInfoV1, bit_width);
    ABI_OFFSET(TCWireInfoV1, reserved1); ABI_OFFSET(TCWireInfoV1, state_byte_offset); ABI_OFFSET(TCWireInfoV1, reserved2);
    ABI_SIZE(TCBoardApiV4); ABI_ALIGN(TCBoardApiV4); ABI_LAYOUT(TCBoardApiV4);
    ABI_OFFSET(TCBoardApiV4, size); ABI_OFFSET(TCBoardApiV4, version); ABI_OFFSET(TCBoardApiV4, context);
    ABI_OFFSET(TCBoardApiV4, get_current); ABI_OFFSET(TCBoardApiV4, validate); ABI_OFFSET(TCBoardApiV4, resolve);
    ABI_OFFSET(TCBoardApiV4, capture_snapshot); ABI_OFFSET(TCBoardApiV4, capture_objects);
    ABI_OFFSET(TCBoardApiV4, read_component); ABI_OFFSET(TCBoardApiV4, read_wire);
    ABI_SIZE(TCPinInfoV1); ABI_ALIGN(TCPinInfoV1); ABI_LAYOUT(TCPinInfoV1);
    ABI_OFFSET(TCPinInfoV1, size); ABI_OFFSET(TCPinInfoV1, version); ABI_OFFSET(TCPinInfoV1, direction);
    ABI_OFFSET(TCPinInfoV1, flags); ABI_OFFSET(TCPinInfoV1, x); ABI_OFFSET(TCPinInfoV1, y);
    ABI_OFFSET(TCPinInfoV1, bits); ABI_OFFSET(TCPinInfoV1, reserved0); ABI_OFFSET(TCPinInfoV1, word_size_raw);
    ABI_SIZE(TCComponentPinsV1); ABI_ALIGN(TCComponentPinsV1); ABI_LAYOUT(TCComponentPinsV1);
    ABI_OFFSET(TCComponentPinsV1, size); ABI_OFFSET(TCComponentPinsV1, version); ABI_OFFSET(TCComponentPinsV1, flags);
    ABI_OFFSET(TCComponentPinsV1, kind); ABI_OFFSET(TCComponentPinsV1, component);
    ABI_OFFSET(TCComponentPinsV1, custom_prototype_id); ABI_OFFSET(TCComponentPinsV1, input_count);
    ABI_OFFSET(TCComponentPinsV1, output_count); ABI_OFFSET(TCComponentPinsV1, pin_written);
    ABI_OFFSET(TCComponentPinsV1, reserved0);
    ABI_SIZE(TCComponentPinBuffersV1); ABI_ALIGN(TCComponentPinBuffersV1); ABI_LAYOUT(TCComponentPinBuffersV1);
    ABI_OFFSET(TCComponentPinBuffersV1, size); ABI_OFFSET(TCComponentPinBuffersV1, version);
    ABI_OFFSET(TCComponentPinBuffersV1, reserved0); ABI_OFFSET(TCComponentPinBuffersV1, reserved1);
    ABI_OFFSET(TCComponentPinBuffersV1, pins); ABI_OFFSET(TCComponentPinBuffersV1, pin_capacity);
    ABI_SIZE(TCBoardApiV5); ABI_ALIGN(TCBoardApiV5); ABI_LAYOUT(TCBoardApiV5);
    ABI_OFFSET(TCBoardApiV5, size); ABI_OFFSET(TCBoardApiV5, version); ABI_OFFSET(TCBoardApiV5, context);
    ABI_OFFSET(TCBoardApiV5, get_current); ABI_OFFSET(TCBoardApiV5, validate); ABI_OFFSET(TCBoardApiV5, resolve);
    ABI_OFFSET(TCBoardApiV5, capture_snapshot); ABI_OFFSET(TCBoardApiV5, capture_objects);
    ABI_OFFSET(TCBoardApiV5, read_component); ABI_OFFSET(TCBoardApiV5, read_wire);
    ABI_OFFSET(TCBoardApiV5, read_component_pins);
    ABI_SIZE(TCWireEndV1); ABI_ALIGN(TCWireEndV1); ABI_LAYOUT(TCWireEndV1);
    ABI_OFFSET(TCWireEndV1, size); ABI_OFFSET(TCWireEndV1, version); ABI_OFFSET(TCWireEndV1, flags);
    ABI_OFFSET(TCWireEndV1, direction); ABI_OFFSET(TCWireEndV1, pin_index); ABI_OFFSET(TCWireEndV1, reserved0);
    ABI_OFFSET(TCWireEndV1, x); ABI_OFFSET(TCWireEndV1, y); ABI_OFFSET(TCWireEndV1, component);
    ABI_SIZE(TCWireEndsV1); ABI_ALIGN(TCWireEndsV1); ABI_LAYOUT(TCWireEndsV1);
    ABI_OFFSET(TCWireEndsV1, size); ABI_OFFSET(TCWireEndsV1, version); ABI_OFFSET(TCWireEndsV1, flags);
    ABI_OFFSET(TCWireEndsV1, reserved0); ABI_OFFSET(TCWireEndsV1, wire); ABI_OFFSET(TCWireEndsV1, ends);
    ABI_SIZE(TCBoardApiV6); ABI_ALIGN(TCBoardApiV6); ABI_LAYOUT(TCBoardApiV6);
    ABI_OFFSET(TCBoardApiV6, size); ABI_OFFSET(TCBoardApiV6, version); ABI_OFFSET(TCBoardApiV6, context);
    ABI_OFFSET(TCBoardApiV6, get_current); ABI_OFFSET(TCBoardApiV6, validate); ABI_OFFSET(TCBoardApiV6, resolve);
    ABI_OFFSET(TCBoardApiV6, capture_snapshot); ABI_OFFSET(TCBoardApiV6, capture_objects);
    ABI_OFFSET(TCBoardApiV6, read_component); ABI_OFFSET(TCBoardApiV6, read_wire);
    ABI_OFFSET(TCBoardApiV6, read_component_pins); ABI_OFFSET(TCBoardApiV6, read_wire_ends);
    ABI_SIZE(TCSimulationStateV1); ABI_ALIGN(TCSimulationStateV1); ABI_LAYOUT(TCSimulationStateV1);
    ABI_OFFSET(TCSimulationStateV1, size); ABI_OFFSET(TCSimulationStateV1, version);
    ABI_OFFSET(TCSimulationStateV1, flags); ABI_OFFSET(TCSimulationStateV1, reserved0);
    ABI_OFFSET(TCSimulationStateV1, cycle); ABI_OFFSET(TCSimulationStateV1, engine_frame);
    ABI_OFFSET(TCSimulationStateV1, state_size); ABI_OFFSET(TCSimulationStateV1, reserved1);
    ABI_SIZE(TCSimulationApiV1); ABI_ALIGN(TCSimulationApiV1); ABI_LAYOUT(TCSimulationApiV1);
    ABI_OFFSET(TCSimulationApiV1, size); ABI_OFFSET(TCSimulationApiV1, version);
    ABI_OFFSET(TCSimulationApiV1, context); ABI_OFFSET(TCSimulationApiV1, get_state);
    ABI_OFFSET(TCSimulationApiV1, read_value);
    ABI_SIZE(TCIoValueApiV1); ABI_ALIGN(TCIoValueApiV1); ABI_LAYOUT(TCIoValueApiV1);
    ABI_OFFSET(TCIoValueApiV1, size); ABI_OFFSET(TCIoValueApiV1, version);
    ABI_OFFSET(TCIoValueApiV1, context); ABI_OFFSET(TCIoValueApiV1, evaluate);
    ABI_OFFSET(TCIoValueApiV1, format_value); ABI_OFFSET(TCIoValueApiV1, read_input);
    ABI_OFFSET(TCIoValueApiV1, write_input); ABI_OFFSET(TCIoValueApiV1, flip_input);
    ABI_OFFSET(TCIoValueApiV1, input_width); ABI_OFFSET(TCIoValueApiV1, write_constant);
    ABI_OFFSET(TCIoValueApiV1, write_constant_slot);
    ABI_SIZE(TCPinOrderEntryV1); ABI_ALIGN(TCPinOrderEntryV1); ABI_LAYOUT(TCPinOrderEntryV1);
    ABI_OFFSET(TCPinOrderEntryV1, key); ABI_OFFSET(TCPinOrderEntryV1, width);
    ABI_OFFSET(TCPinOrderEntryV1, name_size); ABI_OFFSET(TCPinOrderEntryV1, reserved);
    ABI_OFFSET(TCPinOrderEntryV1, name);
    ABI_SIZE(TCPinOrderApiV1); ABI_ALIGN(TCPinOrderApiV1); ABI_LAYOUT(TCPinOrderApiV1);
    ABI_OFFSET(TCPinOrderApiV1, size); ABI_OFFSET(TCPinOrderApiV1, version);
    ABI_OFFSET(TCPinOrderApiV1, context); ABI_OFFSET(TCPinOrderApiV1, count);
    ABI_OFFSET(TCPinOrderApiV1, entry); ABI_OFFSET(TCPinOrderApiV1, move);
    ABI_OFFSET(TCPinOrderApiV1, order); ABI_OFFSET(TCPinOrderApiV1, set_order);
    ABI_OFFSET(TCPinOrderApiV1, reset);
    ABI_SIZE(TCPinOrderBoundsV1); ABI_ALIGN(TCPinOrderBoundsV1); ABI_LAYOUT(TCPinOrderBoundsV1);
    ABI_OFFSET(TCPinOrderBoundsV1, size); ABI_OFFSET(TCPinOrderBoundsV1, version);
    ABI_OFFSET(TCPinOrderBoundsV1, frame); ABI_OFFSET(TCPinOrderBoundsV1, group);
    ABI_OFFSET(TCPinOrderBoundsV1, key); ABI_OFFSET(TCPinOrderBoundsV1, min_x);
    ABI_OFFSET(TCPinOrderBoundsV1, min_y); ABI_OFFSET(TCPinOrderBoundsV1, max_x);
    ABI_OFFSET(TCPinOrderBoundsV1, max_y);
    ABI_SIZE(TCPinOrderApiV2); ABI_ALIGN(TCPinOrderApiV2); ABI_LAYOUT(TCPinOrderApiV2);
    ABI_OFFSET(TCPinOrderApiV2, size); ABI_OFFSET(TCPinOrderApiV2, version);
    ABI_OFFSET(TCPinOrderApiV2, context); ABI_OFFSET(TCPinOrderApiV2, count);
    ABI_OFFSET(TCPinOrderApiV2, entry); ABI_OFFSET(TCPinOrderApiV2, move);
    ABI_OFFSET(TCPinOrderApiV2, order); ABI_OFFSET(TCPinOrderApiV2, set_order);
    ABI_OFFSET(TCPinOrderApiV2, reset); ABI_OFFSET(TCPinOrderApiV2, include_bounds);
    ABI_OFFSET(TCPinOrderApiV2, bounds);
    ABI_SIZE(TCComponentPinInfoV1); ABI_ALIGN(TCComponentPinInfoV1);
    ABI_LAYOUT(TCComponentPinInfoV1);
    ABI_OFFSET(TCComponentPinInfoV1, size); ABI_OFFSET(TCComponentPinInfoV1, reserved);
    ABI_OFFSET(TCComponentPinInfoV1, pin_id); ABI_OFFSET(TCComponentPinInfoV1, direction);
    ABI_OFFSET(TCComponentPinInfoV1, bits); ABI_OFFSET(TCComponentPinInfoV1, name);
    ABI_SIZE(TCComponentTypeInfoV1); ABI_ALIGN(TCComponentTypeInfoV1);
    ABI_LAYOUT(TCComponentTypeInfoV1);
    ABI_OFFSET(TCComponentTypeInfoV1, size); ABI_OFFSET(TCComponentTypeInfoV1, reserved);
    ABI_OFFSET(TCComponentTypeInfoV1, custom_id); ABI_OFFSET(TCComponentTypeInfoV1, gate_cost);
    ABI_OFFSET(TCComponentTypeInfoV1, delay); ABI_OFFSET(TCComponentTypeInfoV1, implementation);
    ABI_OFFSET(TCComponentTypeInfoV1, capabilities);
    ABI_OFFSET(TCComponentTypeInfoV1, schema_version);
    ABI_OFFSET(TCComponentTypeInfoV1, active); ABI_OFFSET(TCComponentTypeInfoV1, input_count);
    ABI_OFFSET(TCComponentTypeInfoV1, output_count);
    ABI_OFFSET(TCComponentTypeInfoV1, pin_limit); ABI_OFFSET(TCComponentTypeInfoV1, type_id);
    ABI_OFFSET(TCComponentTypeInfoV1, name); ABI_OFFSET(TCComponentTypeInfoV1, description);
    ABI_OFFSET(TCComponentTypeInfoV1, owner_mod); ABI_OFFSET(TCComponentTypeInfoV1, status);
ABI_SIZE(TCComponentRegistryApiV1); ABI_ALIGN(TCComponentRegistryApiV1);
ABI_LAYOUT(TCComponentRegistryApiV1);
ABI_OFFSET(TCComponentRegistryApiV1, size); ABI_OFFSET(TCComponentRegistryApiV1, version);
ABI_OFFSET(TCComponentRegistryApiV1, context); ABI_OFFSET(TCComponentRegistryApiV1, count);
ABI_OFFSET(TCComponentRegistryApiV1, get); ABI_OFFSET(TCComponentRegistryApiV1, find);
ABI_OFFSET(TCComponentRegistryApiV1, pin);

/* tc.component.instances V1 and the lifecycle table: the handle a Mod keeps
   across frames, what the host reports about an instance, and the two
   notifications a V2 definition may receive. */
ABI_SIZE(TCComponentInstanceHandle); ABI_ALIGN(TCComponentInstanceHandle);
ABI_LAYOUT(TCComponentInstanceHandle);
ABI_OFFSET(TCComponentInstanceHandle, size); ABI_OFFSET(TCComponentInstanceHandle, version);
ABI_OFFSET(TCComponentInstanceHandle, custom_id);
ABI_OFFSET(TCComponentInstanceHandle, instance_id);
ABI_OFFSET(TCComponentInstanceHandle, generation);
ABI_SIZE(TCComponentInstanceInfoV1); ABI_ALIGN(TCComponentInstanceInfoV1);
ABI_LAYOUT(TCComponentInstanceInfoV1);
ABI_OFFSET(TCComponentInstanceInfoV1, size); ABI_OFFSET(TCComponentInstanceInfoV1, flags);
ABI_OFFSET(TCComponentInstanceInfoV1, handle);
ABI_OFFSET(TCComponentInstanceInfoV1, state_words);
ABI_OFFSET(TCComponentInstanceInfoV1, input_count);
ABI_OFFSET(TCComponentInstanceInfoV1, output_count);
ABI_OFFSET(TCComponentInstanceInfoV1, cycle_calls);
ABI_OFFSET(TCComponentInstanceInfoV1, peeks); ABI_OFFSET(TCComponentInstanceInfoV1, resets);
ABI_OFFSET(TCComponentInstanceInfoV1, type_id); ABI_OFFSET(TCComponentInstanceInfoV1, owner_mod);
ABI_SIZE(TCComponentLifecycleV1); ABI_ALIGN(TCComponentLifecycleV1);
ABI_LAYOUT(TCComponentLifecycleV1);
ABI_OFFSET(TCComponentLifecycleV1, size); ABI_OFFSET(TCComponentLifecycleV1, version);
ABI_OFFSET(TCComponentLifecycleV1, on_create); ABI_OFFSET(TCComponentLifecycleV1, on_destroy);
ABI_OFFSET(TCComponentLifecycleV1, on_config_changed);
ABI_OFFSET(TCComponentLifecycleV1, on_clone);
ABI_OFFSET(TCComponentLifecycleV1, on_load);
ABI_OFFSET(TCComponentLifecycleV1, on_save);
ABI_OFFSET(TCComponentTypeDefinitionV2, lifecycle);
ABI_OFFSET(TCComponentTypeDefinitionV2, config_schema);
ABI_OFFSET(TCComponentTypeDefinitionV2, config_size);
ABI_OFFSET(TCComponentTypeDefinitionV2, default_config);
ABI_OFFSET(TCComponentTypeDefinitionV2, config_migration_version);
ABI_OFFSET(TCComponentTypeDefinitionV2, migrate_config);
ABI_OFFSET(TCComponentTypeDefinitionV2, migration_user);
ABI_SIZE(TCComponentInstancesApiV1); ABI_ALIGN(TCComponentInstancesApiV1);
ABI_LAYOUT(TCComponentInstancesApiV1);
ABI_OFFSET(TCComponentInstancesApiV1, size); ABI_OFFSET(TCComponentInstancesApiV1, version);
ABI_OFFSET(TCComponentInstancesApiV1, context); ABI_OFFSET(TCComponentInstancesApiV1, enumerate);
ABI_OFFSET(TCComponentInstancesApiV1, validate); ABI_OFFSET(TCComponentInstancesApiV1, info);
ABI_OFFSET(TCComponentInstancesApiV1, state); ABI_OFFSET(TCComponentInstancesApiV1, reset);
ABI_CONSTANT(TC_COMPONENT_INSTANCES_API_VERSION_1);
ABI_CONSTANT(TC_COMPONENT_INSTANCES_OK);
ABI_CONSTANT(TC_COMPONENT_LIFECYCLE_VERSION_1);
ABI_CONSTANT(TC_LOGIC_CREATE);
ABI_CONSTANT(TC_LOGIC_DESTROY);
ABI_CONSTANT(TC_LOGIC_CONFIG_CHANGED);
ABI_CONSTANT(TC_LOGIC_CLONE);
ABI_CONSTANT(TC_LOGIC_LOAD);
ABI_CONSTANT(TC_LOGIC_SAVE);

/* tc.component.storage V1: host-owned configuration and state blobs. */
ABI_SIZE(TCComponentStorageInfoV1); ABI_ALIGN(TCComponentStorageInfoV1);
ABI_LAYOUT(TCComponentStorageInfoV1);
ABI_OFFSET(TCComponentStorageInfoV1, size); ABI_OFFSET(TCComponentStorageInfoV1, version);
ABI_OFFSET(TCComponentStorageInfoV1, flags); ABI_OFFSET(TCComponentStorageInfoV1, config_schema);
ABI_OFFSET(TCComponentStorageInfoV1, config_size); ABI_OFFSET(TCComponentStorageInfoV1, state_size);
ABI_OFFSET(TCComponentStorageInfoV1, config_revision); ABI_OFFSET(TCComponentStorageInfoV1, handle);
ABI_SIZE(TCComponentStorageApiV1); ABI_ALIGN(TCComponentStorageApiV1);
ABI_LAYOUT(TCComponentStorageApiV1);
ABI_OFFSET(TCComponentStorageApiV1, size); ABI_OFFSET(TCComponentStorageApiV1, version);
ABI_OFFSET(TCComponentStorageApiV1, context); ABI_OFFSET(TCComponentStorageApiV1, info);
ABI_OFFSET(TCComponentStorageApiV1, read_config); ABI_OFFSET(TCComponentStorageApiV1, write_config);
ABI_OFFSET(TCComponentStorageApiV1, capture_state); ABI_OFFSET(TCComponentStorageApiV1, restore_state);
ABI_SIZE(TCComponentStorageApiV2); ABI_ALIGN(TCComponentStorageApiV2);
ABI_LAYOUT(TCComponentStorageApiV2);
ABI_OFFSET(TCComponentStorageApiV2, size); ABI_OFFSET(TCComponentStorageApiV2, version);
ABI_OFFSET(TCComponentStorageApiV2, context); ABI_OFFSET(TCComponentStorageApiV2, info);
ABI_OFFSET(TCComponentStorageApiV2, read_config); ABI_OFFSET(TCComponentStorageApiV2, write_config);
ABI_OFFSET(TCComponentStorageApiV2, capture_state); ABI_OFFSET(TCComponentStorageApiV2, restore_state);
ABI_OFFSET(TCComponentStorageApiV2, begin_edit); ABI_OFFSET(TCComponentStorageApiV2, commit_edit);
ABI_OFFSET(TCComponentStorageApiV2, abort_edit);
ABI_CONSTANT(TC_COMPONENT_STORAGE_API_VERSION_1);
ABI_CONSTANT(TC_COMPONENT_STORAGE_API_VERSION_2);
ABI_CONSTANT(TC_COMPONENT_STORAGE_INFO_VERSION_1);
ABI_CONSTANT(TC_COMPONENT_STORAGE_OK);
ABI_SIGNED_CONSTANT(TC_COMPONENT_STORAGE_ERR_UNAVAILABLE);
ABI_SIGNED_CONSTANT(TC_COMPONENT_STORAGE_ERR_ARGUMENT);
ABI_SIGNED_CONSTANT(TC_COMPONENT_STORAGE_ERR_STALE);
ABI_SIGNED_CONSTANT(TC_COMPONENT_STORAGE_ERR_SIZE);
ABI_SIGNED_CONSTANT(TC_COMPONENT_STORAGE_ERR_SCHEMA);
ABI_SIGNED_CONSTANT(TC_COMPONENT_STORAGE_ERR_STATE);
ABI_CONSTANT(TC_COMPONENT_STORAGE_HAS_CONFIG);
ABI_CONSTANT(TC_COMPONENT_STORAGE_HAS_STATE);
ABI_CONSTANT(TC_COMPONENT_STORAGE_HAS_PERSISTENCE);

/* tc.component.types V1 and the V2 value model: the pin array a definition
   declares, the register entry, and the callback's IO struct. */
ABI_SIZE(TCComponentPinV2); ABI_ALIGN(TCComponentPinV2); ABI_LAYOUT(TCComponentPinV2);
ABI_OFFSET(TCComponentPinV2, pin_id); ABI_OFFSET(TCComponentPinV2, name);
ABI_OFFSET(TCComponentPinV2, bits); ABI_OFFSET(TCComponentPinV2, reserved);
ABI_SIZE(TCComponentTypeDefinitionV2); ABI_ALIGN(TCComponentTypeDefinitionV2);
ABI_LAYOUT(TCComponentTypeDefinitionV2);
ABI_OFFSET(TCComponentTypeDefinitionV2, size); ABI_OFFSET(TCComponentTypeDefinitionV2, version);
ABI_OFFSET(TCComponentTypeDefinitionV2, custom_id); ABI_OFFSET(TCComponentTypeDefinitionV2, type_id);
ABI_OFFSET(TCComponentTypeDefinitionV2, name); ABI_OFFSET(TCComponentTypeDefinitionV2, description);
ABI_OFFSET(TCComponentTypeDefinitionV2, shape_svg); ABI_OFFSET(TCComponentTypeDefinitionV2, inputs);
ABI_OFFSET(TCComponentTypeDefinitionV2, outputs); ABI_OFFSET(TCComponentTypeDefinitionV2, input_count);
ABI_OFFSET(TCComponentTypeDefinitionV2, output_count); ABI_OFFSET(TCComponentTypeDefinitionV2, state_words);
ABI_OFFSET(TCComponentTypeDefinitionV2, reserved); ABI_OFFSET(TCComponentTypeDefinitionV2, gate_cost);
ABI_OFFSET(TCComponentTypeDefinitionV2, delay); ABI_OFFSET(TCComponentTypeDefinitionV2, callback);
ABI_OFFSET(TCComponentTypeDefinitionV2, user);
ABI_SIZE(TCComponentTypesApiV1); ABI_ALIGN(TCComponentTypesApiV1); ABI_LAYOUT(TCComponentTypesApiV1);
ABI_OFFSET(TCComponentTypesApiV1, size); ABI_OFFSET(TCComponentTypesApiV1, version);
ABI_OFFSET(TCComponentTypesApiV1, context); ABI_OFFSET(TCComponentTypesApiV1, register_definition);

    ABI_SIZE(TCCommandV1); ABI_ALIGN(TCCommandV1); ABI_LAYOUT(TCCommandV1);
    ABI_OFFSET(TCCommandV1, size); ABI_OFFSET(TCCommandV1, type); ABI_OFFSET(TCCommandV1, flags);
    ABI_OFFSET(TCCommandV1, reserved); ABI_OFFSET(TCCommandV1, subject); ABI_OFFSET(TCCommandV1, argument);
    ABI_SIZE(TCCommandStatusV1); ABI_ALIGN(TCCommandStatusV1); ABI_LAYOUT(TCCommandStatusV1);
    ABI_OFFSET(TCCommandStatusV1, size); ABI_OFFSET(TCCommandStatusV1, version); ABI_OFFSET(TCCommandStatusV1, state);
    ABI_OFFSET(TCCommandStatusV1, result); ABI_OFFSET(TCCommandStatusV1, request_id);
    ABI_OFFSET(TCCommandStatusV1, submitted_frame); ABI_OFFSET(TCCommandStatusV1, completed_frame);
    ABI_SIZE(TCCommandApiV1); ABI_ALIGN(TCCommandApiV1); ABI_LAYOUT(TCCommandApiV1);
    ABI_OFFSET(TCCommandApiV1, size); ABI_OFFSET(TCCommandApiV1, version); ABI_OFFSET(TCCommandApiV1, context);
    ABI_OFFSET(TCCommandApiV1, submit); ABI_OFFSET(TCCommandApiV1, get_status); ABI_OFFSET(TCCommandApiV1, cancel);
    ABI_SIZE(TCCommandV2); ABI_ALIGN(TCCommandV2); ABI_LAYOUT(TCCommandV2);
    ABI_OFFSET(TCCommandV2, size); ABI_OFFSET(TCCommandV2, type); ABI_OFFSET(TCCommandV2, flags);
    ABI_OFFSET(TCCommandV2, reserved); ABI_OFFSET(TCCommandV2, subject); ABI_OFFSET(TCCommandV2, argument);
    ABI_OFFSET(TCCommandV2, custom_prototype_id); ABI_OFFSET(TCCommandV2, kind);
    ABI_OFFSET(TCCommandV2, rotation); ABI_OFFSET(TCCommandV2, x); ABI_OFFSET(TCCommandV2, y);
    ABI_OFFSET(TCCommandV2, reserved2); ABI_OFFSET(TCCommandV2, reserved3);
    ABI_SIZE(TCCommandApiV2); ABI_ALIGN(TCCommandApiV2); ABI_LAYOUT(TCCommandApiV2);
    ABI_OFFSET(TCCommandApiV2, size); ABI_OFFSET(TCCommandApiV2, version); ABI_OFFSET(TCCommandApiV2, context);
    ABI_OFFSET(TCCommandApiV2, submit); ABI_OFFSET(TCCommandApiV2, get_status); ABI_OFFSET(TCCommandApiV2, cancel);
    ABI_SIZE(TCTransactionApiV2); ABI_ALIGN(TCTransactionApiV2); ABI_LAYOUT(TCTransactionApiV2);
    ABI_OFFSET(TCTransactionApiV2, size); ABI_OFFSET(TCTransactionApiV2, version);
    ABI_OFFSET(TCTransactionApiV2, context); ABI_OFFSET(TCTransactionApiV2, begin);
    ABI_OFFSET(TCTransactionApiV2, stage); ABI_OFFSET(TCTransactionApiV2, commit);
    ABI_OFFSET(TCTransactionApiV2, abort); ABI_OFFSET(TCTransactionApiV2, get_status);
    ABI_SIZE(TCGameLifecycleEventV1); ABI_ALIGN(TCGameLifecycleEventV1); ABI_LAYOUT(TCGameLifecycleEventV1);
    ABI_OFFSET(TCGameLifecycleEventV1, size); ABI_OFFSET(TCGameLifecycleEventV1, version); ABI_OFFSET(TCGameLifecycleEventV1, kind);
    ABI_OFFSET(TCGameLifecycleEventV1, flags); ABI_OFFSET(TCGameLifecycleEventV1, sequence); ABI_OFFSET(TCGameLifecycleEventV1, engine_frame);
    ABI_OFFSET(TCGameLifecycleEventV1, simulation_cycle); ABI_OFFSET(TCGameLifecycleEventV1, board);
    ABI_OFFSET(TCGameLifecycleEventV1, component_count); ABI_OFFSET(TCGameLifecycleEventV1, wire_count);
    ABI_OFFSET(TCGameLifecycleEventV1, selected_component_count); ABI_OFFSET(TCGameLifecycleEventV1, selected_wire_count);
    ABI_OFFSET(TCGameLifecycleEventV1, user);
    ABI_SIZE(TCGameLifecycleApiV1); ABI_ALIGN(TCGameLifecycleApiV1); ABI_LAYOUT(TCGameLifecycleApiV1);
    ABI_OFFSET(TCGameLifecycleApiV1, size); ABI_OFFSET(TCGameLifecycleApiV1, version);
    ABI_OFFSET(TCGameLifecycleApiV1, context); ABI_OFFSET(TCGameLifecycleApiV1, subscribe);
    ABI_SIZE(TCTransactionStatusV1); ABI_ALIGN(TCTransactionStatusV1); ABI_LAYOUT(TCTransactionStatusV1);
    ABI_OFFSET(TCTransactionStatusV1, size); ABI_OFFSET(TCTransactionStatusV1, version); ABI_OFFSET(TCTransactionStatusV1, state);
    ABI_OFFSET(TCTransactionStatusV1, result); ABI_OFFSET(TCTransactionStatusV1, transaction_id);
    ABI_OFFSET(TCTransactionStatusV1, staged_count); ABI_OFFSET(TCTransactionStatusV1, completed_count);
    ABI_OFFSET(TCTransactionStatusV1, submitted_frame); ABI_OFFSET(TCTransactionStatusV1, completed_frame);
    ABI_SIZE(TCTransactionApiV1); ABI_ALIGN(TCTransactionApiV1); ABI_LAYOUT(TCTransactionApiV1);
    ABI_OFFSET(TCTransactionApiV1, size); ABI_OFFSET(TCTransactionApiV1, version); ABI_OFFSET(TCTransactionApiV1, context);
    ABI_OFFSET(TCTransactionApiV1, begin); ABI_OFFSET(TCTransactionApiV1, stage); ABI_OFFSET(TCTransactionApiV1, commit);
    ABI_OFFSET(TCTransactionApiV1, abort); ABI_OFFSET(TCTransactionApiV1, get_status);

    ABI_SIZE(TCPlugin); ABI_ALIGN(TCPlugin); ABI_LAYOUT(TCPlugin);
    ABI_OFFSET(TCPlugin, size); ABI_OFFSET(TCPlugin, user); ABI_OFFSET(TCPlugin, on_frame); ABI_OFFSET(TCPlugin, on_unload);

    ABI_SIZE(TCLogicIO); ABI_ALIGN(TCLogicIO); ABI_LAYOUT(TCLogicIO);
    ABI_OFFSET(TCLogicIO, size); ABI_OFFSET(TCLogicIO, phase); ABI_OFFSET(TCLogicIO, instance_id);
    ABI_OFFSET(TCLogicIO, cycle); ABI_OFFSET(TCLogicIO, input_count); ABI_OFFSET(TCLogicIO, output_count);
ABI_OFFSET(TCLogicIO, inputs); ABI_OFFSET(TCLogicIO, outputs); ABI_OFFSET(TCLogicIO, state); ABI_OFFSET(TCLogicIO, user);
ABI_SIZE(TCLogicIOV2); ABI_ALIGN(TCLogicIOV2); ABI_LAYOUT(TCLogicIOV2);
ABI_OFFSET(TCLogicIOV2, size); ABI_OFFSET(TCLogicIOV2, version); ABI_OFFSET(TCLogicIOV2, phase);
ABI_OFFSET(TCLogicIOV2, instance_id); ABI_OFFSET(TCLogicIOV2, cycle);
ABI_OFFSET(TCLogicIOV2, input_count); ABI_OFFSET(TCLogicIOV2, output_count);
ABI_OFFSET(TCLogicIOV2, inputs); ABI_OFFSET(TCLogicIOV2, outputs); ABI_OFFSET(TCLogicIOV2, state);
ABI_OFFSET(TCLogicIOV2, state_words); ABI_OFFSET(TCLogicIOV2, reserved); ABI_OFFSET(TCLogicIOV2, user);
ABI_OFFSET(TCLogicIOV2, config); ABI_OFFSET(TCLogicIOV2, config_size); ABI_OFFSET(TCLogicIOV2, config_schema);
    ABI_SIZE(TCLogicDefinition); ABI_ALIGN(TCLogicDefinition); ABI_LAYOUT(TCLogicDefinition);
    ABI_OFFSET(TCLogicDefinition, size); ABI_OFFSET(TCLogicDefinition, version); ABI_OFFSET(TCLogicDefinition, custom_id);
    ABI_OFFSET(TCLogicDefinition, callback); ABI_OFFSET(TCLogicDefinition, user);
    ABI_SIZE(TCComponentPin); ABI_ALIGN(TCComponentPin); ABI_LAYOUT(TCComponentPin);
    ABI_OFFSET(TCComponentPin, name); ABI_OFFSET(TCComponentPin, bits);
    ABI_SIZE(TCNativeComponentDefinition); ABI_ALIGN(TCNativeComponentDefinition); ABI_LAYOUT(TCNativeComponentDefinition);
    ABI_OFFSET(TCNativeComponentDefinition, size); ABI_OFFSET(TCNativeComponentDefinition, custom_id);
    ABI_OFFSET(TCNativeComponentDefinition, name); ABI_OFFSET(TCNativeComponentDefinition, description);
    ABI_OFFSET(TCNativeComponentDefinition, shape_svg); ABI_OFFSET(TCNativeComponentDefinition, input_count);
    ABI_OFFSET(TCNativeComponentDefinition, output_count); ABI_OFFSET(TCNativeComponentDefinition, inputs);
    ABI_OFFSET(TCNativeComponentDefinition, outputs); ABI_OFFSET(TCNativeComponentDefinition, gate_cost);
    ABI_OFFSET(TCNativeComponentDefinition, delay); ABI_OFFSET(TCNativeComponentDefinition, callback);
    ABI_OFFSET(TCNativeComponentDefinition, user);

    ABI_SIZE(TCHookSimDoArgs); ABI_ALIGN(TCHookSimDoArgs); ABI_LAYOUT(TCHookSimDoArgs);
    ABI_OFFSET(TCHookSimDoArgs, size); ABI_OFFSET(TCHookSimDoArgs, command);
    ABI_OFFSET(TCHookSimDoArgs, model); ABI_OFFSET(TCHookSimDoArgs, target);
    ABI_SIZE(TCHookLevelLoadArgs); ABI_ALIGN(TCHookLevelLoadArgs); ABI_LAYOUT(TCHookLevelLoadArgs);
    ABI_OFFSET(TCHookLevelLoadArgs, size); ABI_OFFSET(TCHookLevelLoadArgs, reserved);
    ABI_OFFSET(TCHookLevelLoadArgs, board_model); ABI_OFFSET(TCHookLevelLoadArgs, name);
    ABI_SIZE(TCHookSetCursorPosArgs); ABI_ALIGN(TCHookSetCursorPosArgs);
    ABI_LAYOUT(TCHookSetCursorPosArgs);
    ABI_OFFSET(TCHookSetCursorPosArgs, size); ABI_OFFSET(TCHookSetCursorPosArgs, reserved);
    ABI_OFFSET(TCHookSetCursorPosArgs, x); ABI_OFFSET(TCHookSetCursorPosArgs, y);
    ABI_SIZE(TCHookSetCursorPosYArgs); ABI_ALIGN(TCHookSetCursorPosYArgs);
    ABI_LAYOUT(TCHookSetCursorPosYArgs);
    ABI_OFFSET(TCHookSetCursorPosYArgs, size); ABI_OFFSET(TCHookSetCursorPosYArgs, reserved);
    ABI_OFFSET(TCHookSetCursorPosYArgs, y);
    ABI_SIZE(TCHookCall); ABI_ALIGN(TCHookCall); ABI_LAYOUT(TCHookCall);
    ABI_OFFSET(TCHookCall, size); ABI_OFFSET(TCHookCall, hook_id); ABI_OFFSET(TCHookCall, cycle);
    ABI_OFFSET(TCHookCall, user); ABI_OFFSET(TCHookCall, args); ABI_OFFSET(TCHookCall, skip_original);
    ABI_OFFSET(TCHookCall, reserved); ABI_OFFSET(TCHookCall, run_chain); ABI_OFFSET(TCHookCall, loader_state);
    ABI_OFFSET(TCHookCall, caller);

    ABI_SIZE(TCEvent); ABI_ALIGN(TCEvent); ABI_LAYOUT(TCEvent);
    ABI_OFFSET(TCEvent, size); ABI_OFFSET(TCEvent, kind); ABI_OFFSET(TCEvent, flags); ABI_OFFSET(TCEvent, reserved);
    ABI_OFFSET(TCEvent, cycle); ABI_OFFSET(TCEvent, subject); ABI_OFFSET(TCEvent, name); ABI_OFFSET(TCEvent, user);

    ABI_CONSTANT(TC_MOD_API_VERSION); ABI_CONSTANT(TC_HOST_BASE_SIZE);
    ABI_CONSTANT(TC_CAP_LOG); ABI_CONSTANT(TC_CAP_SYMBOL); ABI_CONSTANT(TC_CAP_HOOK); ABI_CONSTANT(TC_CAP_LOGIC);
    ABI_CONSTANT(TC_CAP_COMPONENT); ABI_CONSTANT(TC_CAP_UI_PAGE); ABI_CONSTANT(TC_CAP_UI_SLOT);
    ABI_CONSTANT(TC_CAP_TEXTURE); ABI_CONSTANT(TC_CAP_STATUS); ABI_CONSTANT(TC_CAP_SYMBOL_ALIAS);
    ABI_CONSTANT(TC_CAP_HOOK_CHAIN); ABI_CONSTANT(TC_CAP_EVENTS);
    ABI_CONSTANT(TC_CAP_GAME_HANDLES);
    ABI_CONSTANT(TC_CAP_SERVICES); ABI_CONSTANT(TC_BOARD_API_VERSION_1); ABI_CONSTANT(TC_BOARD_API_VERSION_2);
    ABI_CONSTANT(TC_BOARD_API_VERSION_3);
    ABI_CONSTANT(TC_BOARD_SNAPSHOT_VERSION_1); ABI_CONSTANT(TC_BOARD_SNAPSHOT_HAS_ENGINE_FRAME);
    ABI_CONSTANT(TC_BOARD_SNAPSHOT_HAS_SIMULATION_CYCLE); ABI_CONSTANT(TC_BOARD_SNAPSHOT_HAS_SELECTION);
    ABI_CONSTANT(TC_BOARD_SNAPSHOT_HAS_PREVIOUS_SELECTION); ABI_CONSTANT(TC_SNAPSHOT_OK);
    ABI_CONSTANT(TC_BOARD_API_VERSION_4); ABI_CONSTANT(TC_COMPONENT_INFO_VERSION_1); ABI_CONSTANT(TC_WIRE_INFO_VERSION_1);
    ABI_CONSTANT(TC_COMPONENT_INFO_HAS_CUSTOM_PROTOTYPE); ABI_CONSTANT(TC_WIRE_INFO_HAS_ENDPOINT);
    ABI_CONSTANT(TC_WIRE_INFO_HAS_WIDTH); ABI_CONSTANT(TC_WIRE_INFO_HAS_STATE_SLOT);
    ABI_CONSTANT(TC_BOARD_API_VERSION_5); ABI_CONSTANT(TC_COMPONENT_PINS_VERSION_1);
    ABI_CONSTANT(TC_PIN_INPUT); ABI_CONSTANT(TC_PIN_OUTPUT); ABI_CONSTANT(TC_PIN_INFO_HAS_POSITION);
    ABI_CONSTANT(TC_PIN_INFO_WIDTH_AUTO); ABI_CONSTANT(TC_BOARD_PINS_HAS_PROTOTYPE);
    ABI_CONSTANT(TC_BOARD_API_VERSION_6); ABI_CONSTANT(TC_WIRE_ENDS_VERSION_1);
    ABI_CONSTANT(TC_WIRE_END_HAS_COMPONENT);
    ABI_CONSTANT(TC_SIMULATION_API_VERSION_1); ABI_CONSTANT(TC_SIMULATION_STATE_VERSION_1);
    ABI_CONSTANT(TC_SIMULATION_STATE_HAS_CYCLE); ABI_CONSTANT(TC_SIMULATION_STATE_HAS_ENGINE_FRAME);
    ABI_CONSTANT(TC_SIMULATION_STATE_HAS_STATE_BUFFER); ABI_CONSTANT(TC_SIMULATION_OK);
    ABI_SIGNED_CONSTANT(TC_SIMULATION_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_SIMULATION_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_SIMULATION_ERR_THREAD); ABI_SIGNED_CONSTANT(TC_SIMULATION_ERR_RANGE);
    ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_STALE); ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_THREAD);
    ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_SIZE); ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_RETRY);
    ABI_SIGNED_CONSTANT(TC_SNAPSHOT_ERR_CAPACITY); ABI_CONSTANT(TC_BOARD_OBJECT_SNAPSHOT_VERSION_1);
    ABI_CONSTANT(TC_BOARD_OBJECT_SNAPSHOT_HAS_COMPONENTS); ABI_CONSTANT(TC_BOARD_OBJECT_SNAPSHOT_HAS_WIRES);
    ABI_CONSTANT(TC_COMMAND_API_VERSION_1); ABI_CONSTANT(TC_COMMAND_SIM_RUN); ABI_CONSTANT(TC_COMMAND_SIM_STOP);
    ABI_CONSTANT(TC_COMMAND_SIM_RESET); ABI_CONSTANT(TC_COMMAND_BOARD_UNDO); ABI_CONSTANT(TC_COMMAND_BOARD_REDO);
    ABI_CONSTANT(TC_COMMAND_SAVE); ABI_CONSTANT(TC_COMMAND_STATE_QUEUED); ABI_CONSTANT(TC_COMMAND_STATE_RUNNING);
    ABI_CONSTANT(TC_COMMAND_STATE_SUCCEEDED); ABI_CONSTANT(TC_COMMAND_STATE_FAILED); ABI_CONSTANT(TC_COMMAND_STATE_CANCELLED);
    ABI_CONSTANT(TC_COMMAND_OK); ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_THREAD); ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_CAPACITY);
    ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_NOT_FOUND); ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_STATE);
    ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_STALE); ABI_SIGNED_CONSTANT(TC_COMMAND_ERR_EXECUTION);
    ABI_CONSTANT(TC_LIFECYCLE_API_VERSION_1); ABI_CONSTANT(TC_LIFECYCLE_EVENT_VERSION_1);
    ABI_CONSTANT(TC_LIFECYCLE_BOARD_ENTERED); ABI_CONSTANT(TC_LIFECYCLE_BOARD_LEFT);
    ABI_CONSTANT(TC_LIFECYCLE_OBJECTS_CHANGED); ABI_CONSTANT(TC_LIFECYCLE_SELECTION_CHANGED);
    ABI_CONSTANT(TC_LIFECYCLE_HAS_OBJECT_COUNTS); ABI_CONSTANT(TC_LIFECYCLE_HAS_SELECTION_COUNTS);
    ABI_CONSTANT(TC_LIFECYCLE_OK); ABI_SIGNED_CONSTANT(TC_LIFECYCLE_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_LIFECYCLE_ERR_ARGUMENT); ABI_SIGNED_CONSTANT(TC_LIFECYCLE_ERR_CAPACITY);
    ABI_CONSTANT(TC_TRANSACTION_API_VERSION_1); ABI_CONSTANT(TC_TRANSACTION_STATUS_VERSION_1);
    ABI_CONSTANT(TC_TRANSACTION_SAVE_ON_COMMIT); ABI_CONSTANT(TC_TRANSACTION_STATE_OPEN);
    ABI_CONSTANT(TC_TRANSACTION_STATE_QUEUED); ABI_CONSTANT(TC_TRANSACTION_STATE_RUNNING);
    ABI_CONSTANT(TC_TRANSACTION_STATE_COMMITTED); ABI_CONSTANT(TC_TRANSACTION_STATE_FAILED);
    ABI_CONSTANT(TC_TRANSACTION_STATE_ABORTED); ABI_CONSTANT(TC_TRANSACTION_STATE_CONFLICT);
    ABI_CONSTANT(TC_TRANSACTION_OK); ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_ARGUMENT); ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_THREAD);
    ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_CAPACITY); ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_NOT_FOUND);
    ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_STATE); ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_STALE);
    ABI_SIGNED_CONSTANT(TC_TRANSACTION_ERR_CONFLICT);
   ABI_CONSTANT(TC_COMMAND_API_VERSION_2); ABI_CONSTANT(TC_COMMAND_BOARD_PLACE_COMPONENT);
    ABI_CONSTANT(TC_COMMAND_BOARD_DUPLICATE_COMPONENT);
    ABI_CONSTANT(TC_TRANSACTION_API_VERSION_2);
    ABI_CONSTANT(TC_UI_SLOT_BOARD_SIDE); ABI_CONSTANT(TC_UI_SLOT_BOARD_TOOLBAR);
    ABI_CONSTANT(TC_LOGIC_RESET); ABI_CONSTANT(TC_LOGIC_REFRESH); ABI_CONSTANT(TC_LOGIC_CYCLE);
    ABI_CONSTANT(TC_HOOK_SIM_DO); ABI_CONSTANT(TC_HOOK_LEVEL_LOAD);
    ABI_CONSTANT(TC_HOOK_SET_CURSOR_POS); ABI_CONSTANT(TC_HOOK_SET_CURSOR_POS_Y); ABI_CONSTANT(TC_HOOK_OK);
    ABI_SIGNED_CONSTANT(TC_HOOK_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_HOOK_ERR_ID);
    ABI_SIGNED_CONSTANT(TC_HOOK_ERR_ARGUMENT); ABI_SIGNED_CONSTANT(TC_HOOK_ERR_CAPACITY); ABI_SIGNED_CONSTANT(TC_HOOK_ERR_TARGET);
    ABI_CONSTANT(TC_EVENT_LEVEL_LOAD); ABI_CONSTANT(TC_EVENT_SCENE_CHANGE); ABI_CONSTANT(TC_EVENT_SIM_COMMAND);
    ABI_CONSTANT(TC_EVENT_SAVE); ABI_CONSTANT(TC_EVENT_OK); ABI_SIGNED_CONSTANT(TC_EVENT_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_EVENT_ERR_ARGUMENT); ABI_SIGNED_CONSTANT(TC_EVENT_ERR_CAPACITY);
    ABI_CONSTANT(TC_GAME_OBJECT_BOARD); ABI_CONSTANT(TC_GAME_OBJECT_COMPONENT); ABI_CONSTANT(TC_GAME_OBJECT_WIRE); ABI_CONSTANT(TC_GAME_OBJECT_LEVEL);
    ABI_CONSTANT(TC_HANDLE_OK); ABI_SIGNED_CONSTANT(TC_HANDLE_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_HANDLE_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_HANDLE_ERR_KIND); ABI_SIGNED_CONSTANT(TC_HANDLE_ERR_STALE);
    ABI_CONSTANT(TC_SERVICE_OK); ABI_SIGNED_CONSTANT(TC_SERVICE_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_SERVICE_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_SERVICE_ERR_VERSION); ABI_SIGNED_CONSTANT(TC_SERVICE_ERR_SIZE);
    ABI_CONSTANT(TC_IO_VALUE_API_VERSION_1); ABI_CONSTANT(TC_IO_VALUE_OK);
    ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_SYNTAX); ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_RANGE);
    ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_STATE); ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_THREAD);
    ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_SIZE); ABI_SIGNED_CONSTANT(TC_IO_VALUE_ERR_INTERNAL);
    ABI_CONSTANT(TC_IO_VALUE_FORMAT_BINARY); ABI_CONSTANT(TC_IO_VALUE_FORMAT_HEX);
    ABI_CONSTANT(TC_IO_VALUE_FORMAT_UNSIGNED); ABI_CONSTANT(TC_IO_VALUE_FORMAT_SIGNED);
    ABI_CONSTANT(TC_PIN_ORDER_API_VERSION_1); ABI_CONSTANT(TC_PIN_ORDER_OK);
    ABI_CONSTANT(TC_PIN_ORDER_API_VERSION_2); ABI_CONSTANT(TC_PIN_ORDER_BOUNDS_VERSION_1);
    ABI_SIGNED_CONSTANT(TC_PIN_ORDER_ERR_UNAVAILABLE); ABI_SIGNED_CONSTANT(TC_PIN_ORDER_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_PIN_ORDER_ERR_GROUP); ABI_SIGNED_CONSTANT(TC_PIN_ORDER_ERR_RANGE);
    ABI_SIGNED_CONSTANT(TC_PIN_ORDER_ERR_STATE);
    ABI_SIGNED_CONSTANT(TC_PIN_ORDER_ERR_NOT_FOUND);
    ABI_CONSTANT(TC_PIN_ORDER_GROUP_INPUTS); ABI_CONSTANT(TC_PIN_ORDER_GROUP_OUTPUTS);
    ABI_CONSTANT(TC_PIN_ORDER_GROUP_MEMORY); ABI_CONSTANT(TC_PIN_ORDER_GROUP_COUNT);
ABI_CONSTANT(TC_COMPONENT_REGISTRY_API_VERSION_1);
ABI_CONSTANT(TC_COMPONENT_TYPES_API_VERSION_1);
ABI_CONSTANT(TC_COMPONENT_TYPES_VERSION_2);
ABI_CONSTANT(TC_COMPONENT_TYPES_OK);
ABI_CONSTANT(TC_COMPONENT_CONFIG_MIGRATION_VERSION_1);
ABI_CONSTANT(TC_COMPONENT_CONFIG_MIGRATE_OK);
ABI_CONSTANT(TC_COMPONENT_CONFIG_MIGRATE_KEEP);
ABI_CONSTANT(TC_COMPONENT_CONFIG_MIGRATE_REJECT);
/* The error codes are negative, and this probe records absolute values only;
   they are documented in the header instead of the baseline. */
ABI_CONSTANT(TC_LOGIC_IO_V2_VERSION_1);
    ABI_CONSTANT(TC_COMPONENT_REGISTRY_OK);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_REGISTRY_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_REGISTRY_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_REGISTRY_ERR_RANGE);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_REGISTRY_ERR_UNKNOWN);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_REGISTRY_ERR_SIZE);
    ABI_CONSTANT(TC_COMPONENT_IMPL_NATIVE_CALLBACK); ABI_CONSTANT(TC_COMPONENT_IMPL_COMPOSITE);
    ABI_CONSTANT(TC_COMPONENT_IMPL_BUILTIN_ALIAS); ABI_CONSTANT(TC_COMPONENT_IMPL_PLACEHOLDER);
    ABI_CONSTANT(TC_COMPONENT_CAP_LOGIC); ABI_CONSTANT(TC_COMPONENT_CAP_WIDE_PIN);
    ABI_CONSTANT(TC_COMPONENT_CAP_MULTI_PIN);
    ABI_CONSTANT(TC_COMPONENT_PIN_INPUT); ABI_CONSTANT(TC_COMPONENT_PIN_OUTPUT);
    /* Component geometry V1 (2026-09-22). */
    ABI_SIZE(TCComponentGeometryApiV1); ABI_ALIGN(TCComponentGeometryApiV1);
    ABI_LAYOUT(TCComponentGeometryApiV1);
    ABI_OFFSET(TCComponentGeometryApiV1, size); ABI_OFFSET(TCComponentGeometryApiV1, version);
    ABI_OFFSET(TCComponentGeometryApiV1, context);
    ABI_OFFSET(TCComponentGeometryApiV1, set_footprint);
    ABI_OFFSET(TCComponentGeometryApiV1, read_footprint);
    ABI_CONSTANT(TC_COMPONENT_GEOMETRY_API_VERSION_1);
    ABI_SIZE(TCComponentGeometryApiV2); ABI_ALIGN(TCComponentGeometryApiV2);
    ABI_LAYOUT(TCComponentGeometryApiV2);
    ABI_OFFSET(TCComponentGeometryApiV2, size); ABI_OFFSET(TCComponentGeometryApiV2, version);
    ABI_OFFSET(TCComponentGeometryApiV2, context);
    ABI_OFFSET(TCComponentGeometryApiV2, set_footprint);
    ABI_OFFSET(TCComponentGeometryApiV2, read_footprint);
    ABI_OFFSET(TCComponentGeometryApiV2, set_instance_footprint);
    ABI_CONSTANT(TC_COMPONENT_GEOMETRY_API_VERSION_2);
    ABI_CONSTANT(TC_COMPONENT_GEOMETRY_OK);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_UNKNOWN);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_OWNERSHIP);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_RANGE);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_GAME);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_THREAD);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_GEOMETRY_ERR_STALE);
    /* Component render V1 overlay slice (2026-09-23). */
    ABI_SIZE(TCComponentRenderDrawV1); ABI_ALIGN(TCComponentRenderDrawV1); ABI_LAYOUT(TCComponentRenderDrawV1);
    ABI_OFFSET(TCComponentRenderDrawV1, size); ABI_OFFSET(TCComponentRenderDrawV1, version);
    ABI_OFFSET(TCComponentRenderDrawV1, context); ABI_OFFSET(TCComponentRenderDrawV1, line);
    ABI_OFFSET(TCComponentRenderDrawV1, rect); ABI_OFFSET(TCComponentRenderDrawV1, rect_filled);
    ABI_OFFSET(TCComponentRenderDrawV1, circle); ABI_OFFSET(TCComponentRenderDrawV1, circle_filled);
    ABI_OFFSET(TCComponentRenderDrawV1, text);
    ABI_SIZE(TCComponentRenderFrameV1); ABI_ALIGN(TCComponentRenderFrameV1); ABI_LAYOUT(TCComponentRenderFrameV1);
    ABI_OFFSET(TCComponentRenderFrameV1, size); ABI_OFFSET(TCComponentRenderFrameV1, version);
    ABI_OFFSET(TCComponentRenderFrameV1, component); ABI_OFFSET(TCComponentRenderFrameV1, custom_id);
    ABI_OFFSET(TCComponentRenderFrameV1, instance_id); ABI_OFFSET(TCComponentRenderFrameV1, rotation);
    ABI_OFFSET(TCComponentRenderFrameV1, origin_x); ABI_OFFSET(TCComponentRenderFrameV1, origin_y);
    ABI_OFFSET(TCComponentRenderFrameV1, axis_x_x); ABI_OFFSET(TCComponentRenderFrameV1, axis_x_y);
    ABI_OFFSET(TCComponentRenderFrameV1, axis_y_x); ABI_OFFSET(TCComponentRenderFrameV1, axis_y_y);
    ABI_OFFSET(TCComponentRenderFrameV1, clip_min_x); ABI_OFFSET(TCComponentRenderFrameV1, clip_min_y);
    ABI_OFFSET(TCComponentRenderFrameV1, clip_max_x); ABI_OFFSET(TCComponentRenderFrameV1, clip_max_y);
    ABI_OFFSET(TCComponentRenderFrameV1, config); ABI_OFFSET(TCComponentRenderFrameV1, config_size);
    ABI_OFFSET(TCComponentRenderFrameV1, config_schema); ABI_OFFSET(TCComponentRenderFrameV1, draw);
    ABI_SIZE(TCComponentRenderApiV1); ABI_ALIGN(TCComponentRenderApiV1); ABI_LAYOUT(TCComponentRenderApiV1);
    ABI_OFFSET(TCComponentRenderApiV1, size); ABI_OFFSET(TCComponentRenderApiV1, version);
    ABI_OFFSET(TCComponentRenderApiV1, context); ABI_OFFSET(TCComponentRenderApiV1, set_draw_callback);
    ABI_SIZE(TCComponentRenderApiV2); ABI_ALIGN(TCComponentRenderApiV2); ABI_LAYOUT(TCComponentRenderApiV2);
    ABI_OFFSET(TCComponentRenderApiV2, size); ABI_OFFSET(TCComponentRenderApiV2, version);
    ABI_OFFSET(TCComponentRenderApiV2, context); ABI_OFFSET(TCComponentRenderApiV2, set_draw_callback);
    ABI_OFFSET(TCComponentRenderApiV2, set_default_drawing);
    ABI_SIZE(TCComponentRenderApiV3); ABI_ALIGN(TCComponentRenderApiV3); ABI_LAYOUT(TCComponentRenderApiV3);
    ABI_OFFSET(TCComponentRenderApiV3, size); ABI_OFFSET(TCComponentRenderApiV3, version);
    ABI_OFFSET(TCComponentRenderApiV3, context); ABI_OFFSET(TCComponentRenderApiV3, set_draw_callback);
    ABI_OFFSET(TCComponentRenderApiV3, set_default_drawing);
    ABI_OFFSET(TCComponentRenderApiV3, set_selection_hint);
    ABI_SIZE(TCComponentRenderApiV4); ABI_ALIGN(TCComponentRenderApiV4); ABI_LAYOUT(TCComponentRenderApiV4);
    ABI_OFFSET(TCComponentRenderApiV4, size); ABI_OFFSET(TCComponentRenderApiV4, version);
    ABI_OFFSET(TCComponentRenderApiV4, context); ABI_OFFSET(TCComponentRenderApiV4, set_draw_callback);
    ABI_OFFSET(TCComponentRenderApiV4, set_default_drawing);
    ABI_OFFSET(TCComponentRenderApiV4, set_selection_hint);
    ABI_OFFSET(TCComponentRenderApiV4, set_foundry_button);
    ABI_SIZE(TCComponentRenderApiV5); ABI_ALIGN(TCComponentRenderApiV5); ABI_LAYOUT(TCComponentRenderApiV5);
    ABI_OFFSET(TCComponentRenderApiV5, size); ABI_OFFSET(TCComponentRenderApiV5, version);
    ABI_OFFSET(TCComponentRenderApiV5, context); ABI_OFFSET(TCComponentRenderApiV5, set_draw_callback);
    ABI_OFFSET(TCComponentRenderApiV5, set_default_drawing);
    ABI_OFFSET(TCComponentRenderApiV5, set_selection_hint);
    ABI_OFFSET(TCComponentRenderApiV5, set_foundry_button);
    ABI_OFFSET(TCComponentRenderApiV5, set_picture);
    ABI_SIZE(TCComponentRenderApiV6); ABI_ALIGN(TCComponentRenderApiV6); ABI_LAYOUT(TCComponentRenderApiV6);
    ABI_OFFSET(TCComponentRenderApiV6, size); ABI_OFFSET(TCComponentRenderApiV6, version);
    ABI_OFFSET(TCComponentRenderApiV6, context); ABI_OFFSET(TCComponentRenderApiV6, set_draw_callback);
    ABI_OFFSET(TCComponentRenderApiV6, set_default_drawing);
    ABI_OFFSET(TCComponentRenderApiV6, set_selection_hint);
    ABI_OFFSET(TCComponentRenderApiV6, set_foundry_button);
    ABI_OFFSET(TCComponentRenderApiV6, set_picture);
    ABI_OFFSET(TCComponentRenderApiV6, set_placement_preview);
    ABI_CONSTANT(TC_COMPONENT_RENDER_API_VERSION_1); ABI_CONSTANT(TC_COMPONENT_RENDER_API_VERSION_2);
    ABI_CONSTANT(TC_COMPONENT_RENDER_API_VERSION_3);
    ABI_CONSTANT(TC_COMPONENT_RENDER_API_VERSION_4);
    ABI_CONSTANT(TC_COMPONENT_RENDER_API_VERSION_5);
    ABI_CONSTANT(TC_COMPONENT_RENDER_API_VERSION_6);
    ABI_CONSTANT(TC_COMPONENT_RENDER_FRAME_VERSION_1);
    ABI_CONSTANT(TC_COMPONENT_RENDER_DRAW_VERSION_1); ABI_CONSTANT(TC_COMPONENT_RENDER_MAX_COMMANDS_PER_INSTANCE);
    ABI_CONSTANT(TC_COMPONENT_RENDER_OK); ABI_SIGNED_CONSTANT(TC_COMPONENT_RENDER_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_RENDER_ERR_ARGUMENT); ABI_SIGNED_CONSTANT(TC_COMPONENT_RENDER_ERR_UNKNOWN);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_RENDER_ERR_OWNERSHIP); ABI_SIGNED_CONSTANT(TC_COMPONENT_RENDER_ERR_CAPACITY);
    ABI_SIGNED_CONSTANT(TC_COMPONENT_RENDER_ERR_THREAD);
    /* Simulation V2 and the wire-channel resolver (2026-09-21). */
    ABI_SIZE(TCSimChannelV1); ABI_ALIGN(TCSimChannelV1); ABI_LAYOUT(TCSimChannelV1);
    ABI_OFFSET(TCSimChannelV1, size); ABI_OFFSET(TCSimChannelV1, version);
    ABI_OFFSET(TCSimChannelV1, channel_id); ABI_OFFSET(TCSimChannelV1, byte_offset);
    ABI_OFFSET(TCSimChannelV1, bits); ABI_OFFSET(TCSimChannelV1, reserved0);
    ABI_SIZE(TCSimulationControlV1); ABI_ALIGN(TCSimulationControlV1);
    ABI_LAYOUT(TCSimulationControlV1);
    ABI_OFFSET(TCSimulationControlV1, size); ABI_OFFSET(TCSimulationControlV1, version);
    ABI_OFFSET(TCSimulationControlV1, slice); ABI_OFFSET(TCSimulationControlV1, requests);
    ABI_OFFSET(TCSimulationControlV1, clamped); ABI_OFFSET(TCSimulationControlV1, last_target);
    ABI_OFFSET(TCSimulationControlV1, last_effective); ABI_OFFSET(TCSimulationControlV1, last_cycle);
    ABI_SIZE(TCSimulationApiV2); ABI_ALIGN(TCSimulationApiV2); ABI_LAYOUT(TCSimulationApiV2);
    ABI_OFFSET(TCSimulationApiV2, size); ABI_OFFSET(TCSimulationApiV2, version);
    ABI_OFFSET(TCSimulationApiV2, context); ABI_OFFSET(TCSimulationApiV2, get_state);
    ABI_OFFSET(TCSimulationApiV2, read_value); ABI_OFFSET(TCSimulationApiV2, cycle);
    ABI_OFFSET(TCSimulationApiV2, state_size); ABI_OFFSET(TCSimulationApiV2, snapshot);
    ABI_OFFSET(TCSimulationApiV2, run_to); ABI_OFFSET(TCSimulationApiV2, run_for);
    ABI_OFFSET(TCSimulationApiV2, pause); ABI_OFFSET(TCSimulationApiV2, reset);
    ABI_OFFSET(TCSimulationApiV2, step); ABI_OFFSET(TCSimulationApiV2, set_slice);
    ABI_OFFSET(TCSimulationApiV2, control);
    ABI_SIZE(TCSimWireChannelV1); ABI_ALIGN(TCSimWireChannelV1); ABI_LAYOUT(TCSimWireChannelV1);
    ABI_OFFSET(TCSimWireChannelV1, size); ABI_OFFSET(TCSimWireChannelV1, version);
    ABI_OFFSET(TCSimWireChannelV1, channel_id); ABI_OFFSET(TCSimWireChannelV1, byte_offset);
    ABI_OFFSET(TCSimWireChannelV1, bits); ABI_OFFSET(TCSimWireChannelV1, wire_id);
    ABI_OFFSET(TCSimWireChannelV1, x1); ABI_OFFSET(TCSimWireChannelV1, x2);
    ABI_SIZE(TCSimChannelApiV1); ABI_ALIGN(TCSimChannelApiV1); ABI_LAYOUT(TCSimChannelApiV1);
    ABI_OFFSET(TCSimChannelApiV1, size); ABI_OFFSET(TCSimChannelApiV1, version);
    ABI_OFFSET(TCSimChannelApiV1, context); ABI_OFFSET(TCSimChannelApiV1, from_wire);
    ABI_OFFSET(TCSimChannelApiV1, resolve);
    ABI_CONSTANT(TC_SIMULATION_API_VERSION_2); ABI_CONSTANT(TC_SIMULATION_CONTROL_VERSION_1);
    ABI_CONSTANT(TCSIM_CHANNEL_VERSION_1); ABI_CONSTANT(TC_SIM_CHANNEL_API_VERSION_1);
    ABI_CONSTANT(TC_SIM_CHANNEL_OK); ABI_SIGNED_CONSTANT(TC_SIMULATION_ERR_STATE);
    ABI_SIGNED_CONSTANT(TC_SIM_CHANNEL_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_SIM_CHANNEL_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_SIM_CHANNEL_ERR_HANDLE);
    ABI_SIGNED_CONSTANT(TC_SIM_CHANNEL_ERR_STATE);
    ABI_SIGNED_CONSTANT(TC_SIM_CHANNEL_ERR_THREAD);
    ABI_CONSTANT(TCSIM_WIRE_CHANNEL_VERSION_1);
    /* Per-cycle capture (2026-09-21). */
    ABI_SIZE(TCCaptureTriggerV1); ABI_ALIGN(TCCaptureTriggerV1); ABI_LAYOUT(TCCaptureTriggerV1);
    ABI_OFFSET(TCCaptureTriggerV1, size); ABI_OFFSET(TCCaptureTriggerV1, version);
    ABI_OFFSET(TCCaptureTriggerV1, channel); ABI_OFFSET(TCCaptureTriggerV1, edge);
    ABI_OFFSET(TCCaptureTriggerV1, value); ABI_OFFSET(TCCaptureTriggerV1, mask);
    ABI_OFFSET(TCCaptureTriggerV1, holdoff);
    ABI_SIZE(TCCaptureStatusV1); ABI_ALIGN(TCCaptureStatusV1); ABI_LAYOUT(TCCaptureStatusV1);
    ABI_OFFSET(TCCaptureStatusV1, size); ABI_OFFSET(TCCaptureStatusV1, version);
    ABI_OFFSET(TCCaptureStatusV1, channel_count); ABI_OFFSET(TCCaptureStatusV1, depth);
    ABI_OFFSET(TCCaptureStatusV1, rows); ABI_OFFSET(TCCaptureStatusV1, written);
    ABI_OFFSET(TCCaptureStatusV1, first_cycle); ABI_OFFSET(TCCaptureStatusV1, last_cycle);
    ABI_OFFSET(TCCaptureStatusV1, gaps); ABI_OFFSET(TCCaptureStatusV1, restarts);
    ABI_OFFSET(TCCaptureStatusV1, trigger_cycle); ABI_OFFSET(TCCaptureStatusV1, triggered);
    ABI_OFFSET(TCCaptureStatusV1, recording); ABI_OFFSET(TCCaptureStatusV1, injected);
    ABI_SIZE(TCCaptureApiV1); ABI_ALIGN(TCCaptureApiV1); ABI_LAYOUT(TCCaptureApiV1);
    ABI_OFFSET(TCCaptureApiV1, size); ABI_OFFSET(TCCaptureApiV1, version);
    ABI_OFFSET(TCCaptureApiV1, context); ABI_OFFSET(TCCaptureApiV1, configure);
    ABI_OFFSET(TCCaptureApiV1, start); ABI_OFFSET(TCCaptureApiV1, stop);
    ABI_OFFSET(TCCaptureApiV1, read); ABI_OFFSET(TCCaptureApiV1, status);
    ABI_CONSTANT(TC_SIM_CAPTURE_API_VERSION_1); ABI_CONSTANT(TC_SIM_CAPTURE_OK);
    ABI_SIGNED_CONSTANT(TC_SIM_CAPTURE_ERR_UNAVAILABLE);
    ABI_SIGNED_CONSTANT(TC_SIM_CAPTURE_ERR_ARGUMENT);
    ABI_SIGNED_CONSTANT(TC_SIM_CAPTURE_ERR_STATE);
    ABI_SIGNED_CONSTANT(TC_SIM_CAPTURE_ERR_RANGE);
    ABI_CONSTANT(TCCAPTURE_EDGE_NONE); ABI_CONSTANT(TCCAPTURE_EDGE_RISING);
    ABI_CONSTANT(TCCAPTURE_EDGE_FALLING); ABI_CONSTANT(TCCAPTURE_EDGE_EITHER);
    ABI_CONSTANT(TCCAPTURE_EDGE_MATCH); ABI_CONSTANT(TCCAPTURE_TRIGGER_VERSION_1);
    ABI_CONSTANT(TCCAPTURE_STATUS_VERSION_1);
    return 0;
}
