param([switch]$Check)

$ErrorActionPreference = 'Stop'
$taskRepo = Split-Path $PSScriptRoot
$taskManifestPath = Join-Path $taskRepo 'compat\profiles.json'
$taskOutputPath = Join-Path $taskRepo 'src\compat.generated.hpp'
$taskManifest = Get-Content -LiteralPath $taskManifestPath -Raw | ConvertFrom-Json

if ([int]$taskManifest.schemaVersion -ne 1) { throw "Unsupported compatibility profile schema: $($taskManifest.schemaVersion)" }
$taskProfiles = @($taskManifest.profiles)
$taskCurrent = @($taskProfiles | Where-Object { $_.current -eq $true })
if ($taskCurrent.Count -ne 1) { throw 'Compatibility profiles must contain exactly one current profile' }
$taskProfile = $taskCurrent[0]
if ([string]$taskProfile.platform -ne 'windows-x64') { throw "Current compatibility profile must target windows-x64" }

function Assert-Identifier([string]$Value, [string]$Label) {
  if ($Value -notmatch '^[A-Z][A-Z0-9_]+$') { throw "Invalid $Label identifier: $Value" }
}
function Assert-Sha256([string]$Value, [string]$Label) {
  if ($Value -notmatch '^[0-9a-f]{64}$') { throw "Invalid SHA-256 for $Label" }
}
function ConvertTo-CppString([string]$Value) {
  return '"' + $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n') + '"'
}

if ([string]$taskProfile.id -notmatch '^[a-z0-9][a-z0-9.-]+$') { throw 'Invalid compatibility profile id' }
Assert-Sha256 ([string]$taskProfile.files.executable.sha256) 'game executable'
Assert-Sha256 ([string]$taskProfile.files.engine.sha256) 'game engine'
if ([long]$taskProfile.files.executable.size -lt 1 -or [long]$taskProfile.files.engine.size -lt 1) { throw 'Profile file sizes must be positive' }

$taskKnownRvas = @(
  'TC_MENU_END_RVA', 'TC_HOME_START_RVA', 'TC_HOME_END_RVA',
  'TC_BOARD_INPUT_SAMPLE_RVA', 'TC_BOARD_TOOLBAR_END_RVA', 'TC_BOARD_WINDOW_HOVER_RVA'
)
$taskRvaNames = @($taskProfile.rvas.PSObject.Properties.Name)
if ((($taskRvaNames | Sort-Object) -join "`n") -cne (($taskKnownRvas | Sort-Object) -join "`n")) {
  throw 'Current profile must declare exactly the loader RVA set expected by this source tree'
}
foreach ($taskName in $taskRvaNames) {
  Assert-Identifier $taskName 'RVA macro'
  if ([string]$taskProfile.rvas.$taskName -notmatch '^0x[0-9a-fA-F]+$') { throw "Invalid RVA value for $taskName" }
}

$taskAliases = @($taskProfile.requiredSymbolAliases | ForEach-Object { [string]$_ })
if (!$taskAliases.Count -or @($taskAliases | Sort-Object -Unique).Count -ne $taskAliases.Count) {
  throw 'Required symbol aliases must be non-empty and unique'
}
$taskSymbolSource = Get-Content -LiteralPath (Join-Path $taskRepo 'src\symbol_profile.hpp') -Raw
foreach ($taskAlias in $taskAliases) {
  $taskNeedle = '{"' + $taskAlias + '",'
  if (!$taskSymbolSource.Contains($taskNeedle)) { throw "Compatibility profile requires missing symbol alias: $taskAlias" }
}
$taskSourceAliases = @([regex]::Matches($taskSymbolSource, '\{"([a-zA-Z0-9_.-]+)",\s*"') | ForEach-Object { $_.Groups[1].Value })
$taskUnexpectedAliases = @($taskSourceAliases | Where-Object { $taskAliases -cnotcontains $_ })
if ($taskUnexpectedAliases.Count) { throw "Symbol profile aliases missing from compatibility profile: $($taskUnexpectedAliases -join ', ')" }

$taskLines = @(
  '#pragma once',
  '/* Generated from compat/profiles.json by tools/generate-compat.ps1.',
  '   Do not edit this file directly. */',
  ('#define TC_COMPAT_PROFILE_ID ' + (ConvertTo-CppString ([string]$taskProfile.id))),
  ('#define TC_GAME_VERSION ' + (ConvertTo-CppString ([string]$taskProfile.gameVersion))),
  ('#define TC_GAME_BUILD_LABEL ' + (ConvertTo-CppString ([string]$taskProfile.gameBuildLabel))),
  ('#define TC_GAME_EXE_NAME ' + (ConvertTo-CppString ([string]$taskProfile.files.executable.name))),
  ('#define TC_GAME_ENGINE_NAME ' + (ConvertTo-CppString ([string]$taskProfile.files.engine.installedName))),
  ('#define TC_GAME_ENGINE_BACKUP_NAME ' + (ConvertTo-CppString ([string]$taskProfile.files.engine.backupName))),
  ('#define TC_EXE_SIZE ' + [string][long]$taskProfile.files.executable.size + 'ULL'),
  ('#define TC_ENGINE_SIZE ' + [string][long]$taskProfile.files.engine.size + 'ULL'),
  ('#define TC_EXE_SHA ' + (ConvertTo-CppString ([string]$taskProfile.files.executable.sha256))),
  ('#define TC_ENGINE_SHA ' + (ConvertTo-CppString ([string]$taskProfile.files.engine.sha256)))
)
foreach ($taskName in $taskKnownRvas) {
  $taskLines += ('#define ' + $taskName + ' ' + [string]$taskProfile.rvas.$taskName + 'ULL')
}
foreach ($taskLoader in $taskProfile.acceptedInstalledLoaders) {
  $taskMacro = [string]$taskLoader.macro
  Assert-Identifier $taskMacro 'loader hash macro'
  Assert-Sha256 ([string]$taskLoader.sha256) "accepted loader $taskMacro"
  $taskLines += ('#define ' + $taskMacro + ' ' + (ConvertTo-CppString ([string]$taskLoader.sha256)))
}
$taskLines += ('#define TC_REQUIRED_SYMBOL_ALIAS_COUNT ' + [string]$taskAliases.Count + 'u')
$taskGenerated = ($taskLines -join "`n") + "`n"

$taskExisting = if (Test-Path -LiteralPath $taskOutputPath) { [IO.File]::ReadAllText($taskOutputPath).Replace("`r`n", "`n") } else { '' }
if ($Check) {
  if ($taskExisting -cne $taskGenerated) { throw 'src/compat.generated.hpp is stale; run tools/generate-compat.ps1' }
  "PASS compatibility profile generation: $($taskProfile.id), $($taskAliases.Count) required aliases"
  exit 0
}
if ($taskExisting -cne $taskGenerated) {
  [IO.File]::WriteAllText($taskOutputPath, $taskGenerated, [Text.UTF8Encoding]::new($false))
  "Generated $taskOutputPath from $taskManifestPath"
}
