#pragma once
/* Generated from compat/profiles.json by tools/generate-compat.ps1.
   Do not edit this file directly. */
#define TC_COMPAT_PROFILE_ID "tc-win64-2.1.334"
#define TC_GAME_VERSION "2.1.334"
#define TC_GAME_BUILD_LABEL "2.1.334 / native-api-1"
#define TC_GAME_EXE_NAME "Turing Complete.exe"
#define TC_GAME_ENGINE_NAME "game_engine.dll"
#define TC_GAME_ENGINE_BACKUP_NAME "tc_game_engine.dll"
#define TC_EXE_SIZE 9752394ULL
#define TC_ENGINE_SIZE 1989120ULL
#define TC_EXE_SHA "8875da0e88cc878cb0fce30cfb63d20c5500cae341608af4d786649b88c8eb21"
#define TC_ENGINE_SHA "0a4030b5f5538cc3682610ac3e7b39e8e31ec34f9aeafe7a1d036bfa33819166"
#define TC_MENU_END_RVA 0x456c33ULL
#define TC_HOME_START_RVA 0x449df0ULL
#define TC_HOME_END_RVA 0x44b610ULL
#define TC_BOARD_INPUT_SAMPLE_RVA 0x46b593ULL
#define TC_BOARD_TOOLBAR_END_RVA 0x4659c1ULL
#define TC_BOARD_WINDOW_HOVER_RVA 0x46b5e2ULL
#define TC_LOADER_020_SHA "1612880bc7c3c198604b5b967900a32720700ebebd135b72348a3e3ac409877b"
#define TC_PREVIOUS_LOADER_SHA "f41ba881ebab46b8cced4eacd76193e1af97004667082b4cff5378b1d81f60c5"
#define TC_REQUIRED_SYMBOL_ALIAS_COUNT 21u
