#pragma once
/* Generated by tools/generate-gate-pins.py from the pinned build's own
   prototype table (build/kinds.txt, 2.1.334).  Do not edit by hand:
   re-run the generator, which also refuses any prototype whose pin
   geometry is incomplete.  Only combinational prototypes are listed -
   see the generator's header for why. */
namespace tc {
namespace gate_delay {

struct KindPins {
    uint8_t kind = 0;
    uint8_t inCount = 0, outCount = 0;
    int8_t inX[8] = {}, inY[8] = {};
    int8_t outX[4] = {}, outY[4] = {};
};

inline const KindPins kBuiltinKindPins[] = {
    {0x03, 1, 1, {-1}, {0}, {2}, {0}},  // NOT
    {0x04, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // AND
    {0x05, 3, 1, {-1, -1, -1}, {-1, 0, 1}, {2}, {0}},  // 3 Pin AND
    {0x06, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // NAND
    {0x07, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // OR
    {0x08, 3, 1, {-1, -1, -1}, {-1, 0, 1}, {2}, {0}},  // 3 Pin OR
    {0x09, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // NOR
    {0x0a, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // XOR
    {0x0b, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // XNOR
    {0x0f, 3, 2, {0, -1, -1}, {-2, -1, 1}, {2, 1}, {0, 2}},  // Full Adder
    {0x12, 1, 1, {-1}, {0}, {2}, {0}},  // NOT
    {0x13, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // OR
    {0x14, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // AND
    {0x15, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // NAND
    {0x16, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // NOR
    {0x17, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // XOR
    {0x18, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // XNOR
    {0x1a, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Equal
    {0x1b, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Low < (unsigned)
    {0x1c, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Less < (signed)
    {0x1d, 1, 1, {-1}, {0}, {2}, {0}},  // Negate
    {0x1e, 3, 2, {-1, -1, 0}, {-1, 1, -2}, {2, 1}, {0, 2}},  // Add
    {0x1f, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Multiply
    {0x20, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Divide
    {0x21, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Shift Left
    {0x22, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Shift Right
    {0x23, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Rotate Left
    {0x24, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Rotate Right
    {0x25, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Arithmetic Shift Right
    {0x2a, 3, 1, {-1, -1, -1}, {-1, 0, 1}, {2}, {0}},  // Mux
    {0x2b, 1, 2, {-1}, {0}, {1, 1}, {0, 1}},  // 1 Bit Decoder
    {0x2c, 1, 4, {-1}, {-1}, {1, 1, 1, 1}, {-1, 0, 1, 2}},  // 2 Bit Decoder
    {0x2f, 1, 2, {-1}, {0}, {1, 1}, {-1, 0}},  // Splitter
    {0x30, 2, 1, {-1, -1}, {-1, 0}, {1}, {0}},  // Word Maker
    {0x31, 1, 1, {-1}, {0}, {2}, {0}},  // Count leading zero
    {0x36, 3, 2, {-15, -15, 0}, {-1, 0, 0}, {16, 1}, {-1, 0}},  // Load port
    {0x39, 1, 1, {-1}, {0}, {2}, {0}},  // Count trailing zero
    {0x61, 4, 1, {-1, -1, -1, -1}, {-1, 0, 1, 2}, {1}, {0}},  // Word Maker
    {0x63, 1, 4, {-1}, {0}, {1, 1, 1, 1}, {-1, 0, 1, 2}},  // Splitter
    {0x65, 1, 1, {-2}, {0}, {2}, {0}},  // Static Indexer
    {0x68, 1, 1, {-1}, {0}, {2}, {0}},  // Increment
    {0x6c, 2, 1, {-1, -1}, {-1, 1}, {2}, {0}},  // Modulo
    {0x6d, 1, 2, {-1}, {0}, {1, 1}, {-1, 0}},  // Splitter
    {0x6e, 1, 4, {-1}, {0}, {1, 1, 1, 1}, {-1, 0, 1, 2}},  // Splitter
    {0x6f, 2, 1, {-1, -1}, {-1, 0}, {1}, {0}},  // Maker
    {0x70, 4, 1, {-1, -1, -1, -1}, {-1, 0, 1, 2}, {1}, {0}},  // Maker
    {0x72, 2, 1, {-1, -1}, {-1, 0}, {1}, {0}},  // Concatenator
    {0x73, 4, 1, {-1, -1, -1, -1}, {-1, 0, 1, 2}, {1}, {0}},  // Concatenator
    {0x75, 3, 1, {-2, -1, 1}, {0, -1, -1}, {2}, {0}},  // Auto Static Indexer
};

inline const KindPins* builtinKindPins(uint8_t kind) {
    for (const KindPins& entry : kBuiltinKindPins)
        if (entry.kind == kind) return &entry;
    return nullptr;
}

}  // namespace gate_delay
}  // namespace tc
